"""An environment where agents must navigate to a room, unlock a door, and pick up a box. The door is blocked by a ball that must be moved first. This is useful for testing and debugging cooperative navigation and manipulation tasks."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/envs/multigrid/06_blockedunlockpickup.ipynb.

# %% ../../../nbs/envs/multigrid/06_blockedunlockpickup.ipynb #5ceaaf47
from __future__ import annotations

from fastcore.utils import patch

from .core.constants import Color, Direction, Type
from .core.mission import MissionSpace
from .roomgrid import RoomGrid
from .core.world_object import Ball


# %% auto #0
__all__ = ['BlockedUnlockPickupEnv']

# %% ../../../nbs/envs/multigrid/06_blockedunlockpickup.ipynb #d712ae23
class BlockedUnlockPickupEnv(RoomGrid):
    "The objective is to pick up a box which is placed in another room, behind a locked door."

    def __init__(
        self,
        room_size: int = 6, # Width and height for each of the two rooms
        max_steps: int | None = None, # Maximum number of steps per episode
        joint_reward: bool = True, # Whether all agents receive the reward when the task is completed
        **kwargs # See `stable_marl.base.MultiGridEnv.__init__`
    ):
        assert room_size >= 4
        mission_space = MissionSpace(
            mission_func=self._gen_mission,
            ordered_placeholders=[list(Color), [Type.box, Type.key]],
        )
        # super()
        RoomGrid.__init__(
            self= self,
            mission_space=mission_space,
            num_rows=1,
            num_cols=2,
            room_size=room_size,
            max_steps=max_steps or (16 * room_size**2),
            joint_reward=joint_reward,
            success_termination_mode='any',
            **kwargs,
        )

    

    @staticmethod
    def _gen_mission(color: str, obj_type: str):
        return f"pick up the {Color(color).value} {Type(obj_type).value}"

    def _gen_grid(self, width, height):
        pass

# %% ../../../nbs/envs/multigrid/06_blockedunlockpickup.ipynb #c8daf676
@patch
def _gen_grid(self: BlockedUnlockPickupEnv, width, height):
    # super()
    RoomGrid._gen_grid(self, width, height)

    # Add a box to the room on the right
    self.obj, _ = self.add_object(1, 0, kind=Type.box)

    # Make sure the two rooms are directly connected by a locked door
    door, pos = self.add_door(0, 0, Direction.right, locked=True)

    # Block the door with a ball
    self.grid.set(pos[0] - 1, pos[1], Ball(color=self._rand_color()))

    # Add a key to unlock the door
    self.add_object(0, 0, Type.key, door.color)

    # Place agents in the left room
    for agent in self.agents:
        self.place_agent(agent, 0, 0)

    self.mission = self.mission_space.get((
        list(Color).index(self.obj.color), [Type.box, Type.key].index(self.obj.type)))


# %% ../../../nbs/envs/multigrid/06_blockedunlockpickup.ipynb #16b13f48
@patch
def step(self: BlockedUnlockPickupEnv, actions):
    obs, reward, terminated, truncated, info = RoomGrid.step(self, actions)
    for agent in self.agents:
        if agent.state.carrying == self.obj:
            self.on_success(agent, reward, terminated)

    return obs, reward, terminated, truncated, info


# %% ../../../nbs/envs/multigrid/06_blockedunlockpickup.ipynb #4b9e2f7a
@patch
def on_toggle(self: BlockedUnlockPickupEnv, agent, obj, pos, rewards):
    if obj is self.obj:
        self.agent_states.terminated = True

