"""Scripted MultiGrid policies with access to the true env state, e.g. to collect expert data."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/envs/multigrid/12_expert.ipynb.

# %% ../../../nbs/envs/multigrid/12_expert.ipynb #24a78896
from __future__ import annotations

from collections import deque

import numpy as np

from ...policy import ExpertPolicy
from .base import MultiGridEnv
from .core.actions import Action
from .core.constants import Direction
from .core.world_object import Goal

# %% auto #0
__all__ = ['GoToGoalPolicy', 'goal_distances']

# %% ../../../nbs/envs/multigrid/12_expert.ipynb #bf07f456
class GoToGoalPolicy(ExpertPolicy):
    """
    Navigation expert (e.g. for the Empty and FindGoal envs): every agent follows a shortest
    path to the nearest goal, over the cells it can walk on, turning towards the next cell
    and then moving forward.

    Agents without a path to a goal (or already terminated) turn left. Other agents are not
    treated as obstacles.
    """
    def act(self, env: MultiGridEnv) -> np.ndarray:
        distance = goal_distances(env)
        return np.array([self._agent_action(env, agent, distance) for agent in env.agents])

    @staticmethod
    def _agent_action(env: MultiGridEnv, agent, distance: np.ndarray) -> int:
        x, y = (int(v) for v in agent.state.pos)
        if agent.state.terminated or not np.isfinite(distance[x, y]) or distance[x, y] == 0:
            return int(Action.left)
        current = int(agent.state.dir)
        # directions towards a neighbour one step closer to a goal, preferring the current one
        closer = [d for d in Direction if _distance_at(distance, (x, y) + d.to_vec()) == distance[x, y] - 1]
        if current in closer:
            return int(Action.forward)
        if (current + 1) % 4 in closer:
            return int(Action.right)
        return int(Action.left)


def _distance_at(distance: np.ndarray, pos) -> float:
    x, y = pos
    w, h = distance.shape
    return distance[x, y] if 0 <= x < w and 0 <= y < h else np.inf


def goal_distances(env: MultiGridEnv) -> np.ndarray:
    "Number of steps from every cell to the nearest goal, walking on overlappable cells (inf: unreachable)."
    distance = np.full((env.width, env.height), np.inf)
    queue = deque()
    for x in range(env.width):
        for y in range(env.height):
            if isinstance(env.grid.get(x, y), Goal):
                distance[x, y] = 0
                queue.append((x, y))
    while queue:
        x, y = queue.popleft()
        for d in Direction:
            nx, ny = (int(v) for v in (x, y) + d.to_vec())
            if not (0 <= nx < env.width and 0 <= ny < env.height) or np.isfinite(distance[nx, ny]):
                continue
            cell = env.grid.get(nx, ny)
            if cell is None or cell.can_overlap():
                distance[nx, ny] = distance[x, y] + 1
                queue.append((nx, ny))
    return distance
