"""An environment where agents must navigate to a room, unlock a door, and pick up a box. The door is blocked by a ball that must be moved first. This is useful for testing and debugging cooperative navigation and manipulation tasks."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/envs/multigrid/07_locked_hallway.ipynb.

# %% ../../../nbs/envs/multigrid/07_locked_hallway.ipynb #6192f492
from __future__ import annotations

from math import ceil
from fastcore.utils import patch

from .base import MultiGridEnv
from .core.actions import Action
from .core.constants import Color, Direction
from .core.mission import MissionSpace
from .roomgrid import Room, RoomGrid
from .core.world_object import Door, Key



# %% auto #0
__all__ = ['LockedHallwayEnv']

# %% ../../../nbs/envs/multigrid/07_locked_hallway.ipynb #866a0f29
class LockedHallwayEnv(RoomGrid):
    """
    .. image:: https://i.imgur.com/VylPtnn.gif
        :width: 325

    ***********
    Description
    ***********

    This environment consists of a hallway with multiple locked rooms on either side.
    To unlock each door, agents must first find the corresponding key,
    which may be in another locked room. Agents are rewarded for each door they unlock.

    The standard setting is cooperative, where all agents receive a reward
    for each door that is opened.

    *************
    Mission Space
    *************

    "unlock all the doors"

    *****************
    Observation Space
    *****************

    The multi-agent observation space is a Dict mapping from agent index to
    corresponding agent observation space.

    Each agent observation is a dictionary with the following entries:

    * image : ndarray[int] of shape (view_size, view_size, :attr:`.WorldObj.dim`)
        Encoding of the agent's partially observable view of the environment,
        where each grid cell is encoded as a 3 dimensional tuple:
        (:class:`.Type`, :class:`.Color`, :class:`.State`)
    * direction : int
        Agent's direction (0: right, 1: down, 2: left, 3: up)
    * mission : Mission
        Task string corresponding to the current environment configuration

    ************
    Action Space
    ************

    The multi-agent action space is a Dict mapping from agent index to
    corresponding agent action space.

    Agent actions are discrete integer values, given by:

    +-----+--------------+-----------------------------+
    | Num | Name         | Action                      |
    +=====+==============+=============================+
    | 0   | left         | Turn left                   |
    +-----+--------------+-----------------------------+
    | 1   | right        | Turn right                  |
    +-----+--------------+-----------------------------+
    | 2   | forward      | Move forward                |
    +-----+--------------+-----------------------------+
    | 3   | pickup       | Pick up an object           |
    +-----+--------------+-----------------------------+
    | 4   | drop         | Drop an object              |
    +-----+--------------+-----------------------------+
    | 5   | toggle       | Toggle / activate an object |
    +-----+--------------+-----------------------------+
    | 6   | done         | Done completing task        |
    +-----+--------------+-----------------------------+

    *******
    Rewards
    *******

    A reward of ``1 - 0.9 * (step_count / max_steps)`` is given
    when a door is unlocked.

    ***********
    Termination
    ***********

    The episode ends if any one of the following conditions is met:

    * All doors are unlocked
    * Timeout (see ``max_steps``)

    *************************
    Registered Configurations
    *************************

    * ``MultiGrid-LockedHallway-2Rooms-v0``
    * ``MultiGrid-LockedHallway-4Rooms-v0``
    * ``MultiGrid-LockedHallway-6Rooms-v0``
    """

    def __init__(
        self,
        num_rooms: int = 6,
        room_size: int = 5,
        max_hallway_keys: int = 1,
        max_keys_per_room: int = 2,
        max_steps: int | None = None,
        joint_reward: bool = True,
        **kwargs):
        """
        Parameters
        ----------
        num_rooms : int, default=6
            Number of rooms in the environment
        room_size : int, default=5
            Width and height for each of the rooms
        max_hallway_keys : int, default=1
            Maximum number of keys in the hallway
        max_keys_per_room : int, default=2
            Maximum number of keys in each room
        max_steps : int, optional
            Maximum number of steps per episode
        joint_reward : bool, default=True
            Whether all agents receive the same reward
        **kwargs
            See :attr:`stable_marl.base.MultiGridEnv.__init__`
        """
        assert room_size >= 4
        assert num_rooms % 2 == 0

        self.num_rooms = num_rooms
        self.max_hallway_keys = max_hallway_keys
        self.max_keys_per_room = max_keys_per_room

        if max_steps is None:
            max_steps = 8 * num_rooms * room_size**2

        # super()
        RoomGrid.__init__(
            self= self,
            mission_space=MissionSpace.from_string("unlock all the doors"),
            room_size=room_size,
            num_rows=(num_rooms // 2),
            num_cols=3,
            max_steps=max_steps,
            joint_reward=joint_reward,
            **kwargs,
        )
        

    def _gen_grid(self, width, height):
        pass

# %% ../../../nbs/envs/multigrid/07_locked_hallway.ipynb #e8188d3d
@patch
def _gen_grid(self: LockedHallwayEnv, width, height):
    """
    :meta private:
    """
    #super()
    RoomGrid._gen_grid(self, width, height)

    LEFT, HALLWAY, RIGHT = range(3) # columns
    color_sequence = list(Color) * ceil(self.num_rooms / len(Color))
    color_sequence = self._rand_perm(color_sequence)[:self.num_rooms]

    # Create hallway
    for row in range(self.num_rows - 1):
        self.remove_wall(HALLWAY, row, Direction.down)

    # Add doors
    # (colors repeat when num_rooms > len(Color): a key then opens every door of its color,
    #  so keys only need to be placed in one room per color)
    self.rooms: dict[Color, Room] = {}
    self.locked_doors: list[Door] = []
    door_colors = self._rand_perm(color_sequence)
    for row in range(self.num_rows):
        for col, dir in ((LEFT, Direction.right), (RIGHT, Direction.left)):
            color = door_colors.pop()
            self.rooms.setdefault(color, self.get_room(col, row))
            door, _ = self.add_door(
                col, row, dir=dir, color=color, locked=True, rand_pos=False)
            self.locked_doors.append(door)

    # Place keys in hallway
    num_hallway_keys = self._rand_int(1, self.max_hallway_keys + 1)
    hallway_top = self.get_room(HALLWAY, 0).top
    hallway_size = (self.get_room(HALLWAY, 0).size[0], self.height)
    for key_color in color_sequence[:num_hallway_keys]:
        self.place_obj(Key(color=key_color), top=hallway_top, size=hallway_size)

    # Place keys in rooms
    key_index = num_hallway_keys
    while key_index < len(color_sequence):
        room = self.rooms[color_sequence[key_index - 1]]
        num_room_keys = self._rand_int(1, self.max_keys_per_room + 1)
        for key_color in color_sequence[key_index : key_index + num_room_keys]:
            self.place_obj(Key(color=key_color), top=room.top, size=room.size)
            key_index += 1

    # Place agents in hallway
    for agent in self.agents:
        MultiGridEnv.place_agent(self, agent, top=hallway_top, size=hallway_size)

# %% ../../../nbs/envs/multigrid/07_locked_hallway.ipynb #795556ff
@patch
def reset(self: LockedHallwayEnv, **kwargs):
    """
    :meta private:
    """
    self.unlocked_doors = []
    # return super().reset(**kwargs)
    return RoomGrid.reset(self, **kwargs)

# %% ../../../nbs/envs/multigrid/07_locked_hallway.ipynb #5b8cc1e1
@patch
def on_toggle(self: LockedHallwayEnv, agent, obj, pos, rewards):
    """
    :meta private:

    Reward agents for unlocking each locked door (once per door), and end the
    episode once every door has been unlocked.
    """
    if obj in self.locked_doors and not obj.is_locked and obj not in self.unlocked_doors:
        self.unlocked_doors.append(obj)
        if self.joint_reward:
            for i in rewards:
                rewards[i] += self._reward()
        else:
            rewards[agent.index] += self._reward()

        # All doors unlocked: success for every agent
        if len(self.unlocked_doors) == len(self.locked_doors):
            self.agent_states.terminated = True

