"""Environment with multiple rooms and random objects. This environment has no specific goals or rewards."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/envs/multigrid/08_playground.ipynb.

# %% ../../../nbs/envs/multigrid/08_playground.ipynb #cc32d015
from __future__ import annotations

from fastcore.utils import patch

from .core.mission import MissionSpace
from .roomgrid import RoomGrid


# %% auto #0
__all__ = ['PlaygroundEnv']

# %% ../../../nbs/envs/multigrid/08_playground.ipynb #9ea98b4c
class PlaygroundEnv(RoomGrid):
    "Several rooms joined by doors, with random objects and no task (for exploration)."

    def __init__(
        self,
        room_size: int = 7, # Width and height for each of the rooms
        num_rows: int = 3, # Number of rows of rooms
        num_cols: int = 3, # Number of columns of rooms
        max_steps: int = 100, # Maximum number of steps per episode
        **kwargs # See `stable_marl.base.MultiGridEnv.__init__`
    ):
        # super()
        RoomGrid.__init__(
            self= self,
            mission_space=MissionSpace.from_string(""),
            num_rows=num_rows,
            num_cols=num_cols,
            room_size=room_size,
            max_steps=max_steps,
            **kwargs,
        )
        
    def _gen_grid(self, width, height):
        pass

# %% ../../../nbs/envs/multigrid/08_playground.ipynb #e1895990
@patch
def _gen_grid(self: PlaygroundEnv, width, height):
    # super()
    RoomGrid._gen_grid(self, width, height)
    self.connect_all()

    # Place random objects in the world
    for i in range(0, 12):
        col = self._rand_int(0, self.num_cols)
        row = self._rand_int(0, self.num_rows)
        self.add_object(col, row)

    # Place agents
    for agent in self.agents:
        self.place_agent(agent)

