"""Every stable-marl environment, by family, behind one registry."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/envs/02_init.ipynb.

# %% auto #0
__all__ = ['MultiAgentEnv', 'EnvSpec', 'register', 'make', 'make_env', 'list_envs', 'multigrid', 'rware', 'vmas', 'robofactory']

# %% ../../nbs/envs/02_init.ipynb #e944652b
from .base import MultiAgentEnv
from .registry import EnvSpec, register, make, make_env, list_envs
from . import multigrid  # registers the MultiGrid environments
from . import rware      # registers the RWARE environments
from . import vmas       # registers the VMAS environments (created with the `vmas` package)
from . import robofactory   # registers the RoboFactory environments (created with ManiSkill)

_all_ = ['MultiAgentEnv', 'EnvSpec', 'register', 'make', 'make_env', 'list_envs', 'multigrid', 'rware', 'vmas', 'robofactory']
