"""The interface every stable-marl environment implements."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/envs/00_base.ipynb.

# %% ../../nbs/envs/00_base.ipynb #00c8317f
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

import gymnasium as gym
from gymnasium import spaces

from ..types import AgentID

# %% auto #0
__all__ = ['MultiAgentEnv']

# %% ../../nbs/envs/00_base.ipynb #55a2abce
class MultiAgentEnv(gym.Env, ABC):
    "Base class of every stable-marl environment: a gymnasium env with the parallel multi-agent API."
    num_agents: int
    noop_action: Any = None

    @property
    def agent_ids(self) -> list[AgentID]:
        "Ids of all agents, `0 .. num_agents - 1`."
        return list(range(self.num_agents))

    @property
    @abstractmethod
    def state_space(self) -> spaces.Space:
        "Space of the global state returned by `state`."

    @abstractmethod
    def state(self) -> Any:
        "Global (fully observable) state of the environment."
