[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "multigrid"
dynamic = ["version"]
description = "Fast and flexible multi-agent gridworld reinforcement learning environments."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "Ahmed-Khaled-Saleh", email = "ahmedkhaledsaleh11@gmail.com"}]
keywords = ['nbdev']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    'aenum',
    'numpy',
    'pandas',
    'numba',
    'fastcore',
    'nbdev',
    'notebook',
    'jupyterlab',
    'ipywidgets',
    'jupyterlab-git',
    'ipdb',
    # 'pygame',
    'torch',
    'torchvision',
    'lightning',
    'torchmetrics',
    'transformers',
    'timm',
    'peft',
    'datasets',
    "pyarrow==20.0.0",
    "minari[hdf5]>=0.5.3",
    "scikit-learn>=1.7.0",
    "swig",
    "autorom",
    'gymnasium',
    "gymnasium_robotics[mujoco-py]",
    # "pettingzoo[all]",
    "stable-baselines3[extra]",
    'torchrl>=0.10,<0.12',
    'vmas>=1.3.4',
    'ray[rllib]',
    'loguru',
    'tabulate',
    'python-dotenv',
    'einops',
    'tqdm',
    'pillow>=11.3.0',
    'omegaconf',
    'h5py',
    'hydra-core',
    'hydra-submitit-launcher',
    'ujson',
    'gdown',
    'wandb',
    'prettytable',
]

[project.urls]
Repository = "https://github.com/Ahmed-Khaled-Saleh/multigrid"
Documentation = "https://Ahmed-Khaled-Saleh.github.io/multigrid/"

[project.entry-points.nbdev]
multigrid = "multigrid._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "multigrid.__version__"}

[tool.setuptools.packages.find]
include = ["multigrid"]

[tool.setuptools.package-data]
multigrid = ["configs/**/*.yaml"]

[tool.nbdev]
