"""
RoboFactory's tasks, scenes and motion-planning experts, vendored from https://github.com/MARS-EAI/RoboFactory
(MIT, see LICENSE and README.md here). Not generated by nbdev; use it through :mod:`stable_marl.envs.robofactory`.
"""
import os
PACKAGE_DIR = os.path.dirname(__file__)
CONFIG_DIR = os.path.join(PACKAGE_DIR, 'configs')
# stable-marl: the 3D assets are downloaded outside the package (`stable_marl.envs.robofactory.download_assets`)
from ..env import asset_dir
ASSET_DIR = asset_dir()
DIR_MAP = {
    '${PACKAGE_DIR}': PACKAGE_DIR,
    '${ASSET_DIR}': ASSET_DIR,
    '${CONFIG_DIR}': CONFIG_DIR,
}

from .tasks import *
from .planner import *
