"""Put everything about a step in one info dict, like stable-worldmodel's `MegaWrapper`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/wrappers/02_default.ipynb.

# %% ../../nbs/wrappers/02_default.ipynb #631d14a2
from __future__ import annotations

import re
import time
from typing import Any, Callable, Iterable

import gymnasium as gym
import numpy as np

# %% auto #0
__all__ = ['EverythingToInfoWrapper', 'AddPixelsWrapper', 'EnsureInfoKeysWrapper', 'MegaWrapper']

# %% ../../nbs/wrappers/02_default.ipynb #2eb79bf7
def _is_array_like(value) -> bool:
    return isinstance(value, (np.ndarray, np.generic, bool, int, float)) and not isinstance(value, str)


def _stack_agents(values: list) -> Any:
    "The values of all agents, stacked (a list if they are not arrays)."
    return np.stack([np.asarray(v) for v in values]) if all(_is_array_like(v) for v in values) else list(values)


class EverythingToInfoWrapper(gym.Wrapper):
    "Moves everything about a step into one flat info dict (see the table above)."

    def __init__(self, env: gym.Env):
        super().__init__(env)
        self._step_counter, self._id, self._seed = 0, 0, -1

    @property
    def num_agents(self) -> int:
        return self.env.unwrapped.num_agents

    def _info(self, obs: dict, rewards, terminations, truncations, actions, env_infos: dict) -> dict:
        A = self.num_agents
        info = {key: _stack_agents([obs[a][key] for a in range(A)]) for key in obs[0]}
        for key in (env_infos.get(0) or {}):
            assert key not in info, f"info key {key!r} is also an observation key"
            info[key] = _stack_agents([env_infos[a].get(key) for a in range(A)])
        for key, value in (('reward', np.array([rewards[a] for a in range(A)], np.float32)),
                           ('terminated', np.array([terminations[a] for a in range(A)], bool)),
                           ('truncated', np.array([truncations[a] for a in range(A)], bool)),
                           ('action', np.asarray(actions, np.float32).reshape(A)),
                           ('state', self.env.unwrapped.state()),
                           ('step_idx', np.int64(self._step_counter)),
                           ('id', np.int64(self._id)),
                           ('seed', np.int64(self._seed))):
            assert key not in info, f"{key!r} is reserved, the env cannot use it as an observation or info key"
            info[key] = value
        return info

    def reset(self, *, seed: int | None = None, options: dict | None = None):
        obs, env_infos = self.env.reset(seed=seed, options=options)
        self._step_counter, self._seed = 0, -1 if seed is None else int(seed)
        # episode id: from the seed (reproducible), without touching the env's own RNG
        rng = np.random.default_rng(None if seed is None else [int(seed), 0x5EED])
        self._id = int(rng.integers(np.iinfo(np.int64).max))
        A, nan = self.num_agents, [np.nan] * self.num_agents
        return obs, self._info(obs, nan, [False] * A, [False] * A, nan, env_infos)

    def step(self, actions: dict):
        obs, rewards, terminations, truncations, env_infos = self.env.step(actions)
        self._step_counter += 1
        acts = [np.asarray(actions[a]) for a in range(self.num_agents)]
        info = self._info(obs, rewards, terminations, truncations, acts, env_infos)
        return obs, rewards, terminations, truncations, info

# %% ../../nbs/wrappers/02_default.ipynb #c831a84a
_RESAMPLE = {'nearest': 'NEAREST', 'bilinear': 'BILINEAR', 'bicubic': 'BICUBIC',
             'lanczos': 'LANCZOS', 'box': 'BOX', 'hamming': 'HAMMING'}


def _resolve_resample(resample: str | int | None) -> int | None:
    if resample is None or isinstance(resample, int):
        return resample
    from PIL import Image
    if resample not in _RESAMPLE:
        raise ValueError(f"image_resample must be one of {sorted(_RESAMPLE)}, got {resample!r}")
    return getattr(Image.Resampling, _RESAMPLE[resample])


class AddPixelsWrapper(gym.Wrapper):
    """
    Adds a render of the whole env (``env.render()``, so ``render_mode='rgb_array'``) to the
    info as ``pixels``, resized to `image_shape` (H, W) if given, then passed through
    `transform`. Also adds ``render_time`` (seconds).
    """
    def __init__(
        self,
        env: gym.Env,
        image_shape: tuple[int, int] | None = None,
        transform: Callable[[np.ndarray], Any] | None = None,
        resample: str | int | None = None):
        super().__init__(env)
        if env.render_mode != 'rgb_array':
            raise ValueError("AddPixelsWrapper needs an env made with render_mode='rgb_array'")
        self.image_shape, self.transform = image_shape, transform
        self.resample = _resolve_resample(resample)

    def _add_pixels(self, info: dict) -> dict:
        start = time.time()
        img = self.env.render()
        if self.image_shape is not None and img.shape[:2] != tuple(self.image_shape):
            from PIL import Image
            h, w = self.image_shape
            resample = Image.Resampling.BILINEAR if self.resample is None else self.resample
            img = np.asarray(Image.fromarray(img).resize((w, h), resample=resample))
        info['pixels'] = self.transform(img) if self.transform else img
        info['render_time'] = time.time() - start
        return info

    def reset(self, **kwargs):
        obs, info = self.env.reset(**kwargs)
        return obs, self._add_pixels(info)

    def step(self, actions):
        obs, rewards, terminations, truncations, info = self.env.step(actions)
        return obs, rewards, terminations, truncations, self._add_pixels(info)

# %% ../../nbs/wrappers/02_default.ipynb #a097d89b
class EnsureInfoKeysWrapper(gym.Wrapper):
    "Checks that the info of every reset and step has the `required_keys` (regular expressions)."

    def __init__(self, env: gym.Env, required_keys: Iterable[str]):
        super().__init__(env)
        self._patterns = [re.compile(key) for key in required_keys]

    def _check(self, info: dict, where: str):
        for pattern in self._patterns:
            if not any(pattern.fullmatch(key) for key in info):
                raise RuntimeError(f"{where}: no info key matches the required {pattern.pattern!r} "
                                   f"(keys: {sorted(info)})")

    def reset(self, **kwargs):
        obs, info = self.env.reset(**kwargs)
        self._check(info, 'reset')
        return obs, info

    def step(self, actions):
        obs, rewards, terminations, truncations, info = self.env.step(actions)
        self._check(info, 'step')
        return obs, rewards, terminations, truncations, info

# %% ../../nbs/wrappers/02_default.ipynb #fbefe488
class MegaWrapper(gym.Wrapper):
    """
    The standard preprocessing of every env of a :class:`World`: everything goes to the info dict
    (:class:`EverythingToInfoWrapper`), plus the render as ``pixels`` if `add_pixels`
    (:class:`AddPixelsWrapper`), and a check of the `required_keys`.

    Parameters
    ----------
    image_shape : (H, W), optional
        Size ``pixels`` is resized to (default: the render's size)
    pixels_transform : callable, optional
        Applied to ``pixels``
    required_keys : list of str, optional
        Info keys (regular expressions) that must be present
    image_resample : str or int, optional
        PIL resampling used to resize ``pixels`` ('nearest', 'bilinear', ...), default bilinear
    add_pixels : bool
        Render the env into ``pixels`` (needs ``render_mode='rgb_array'``)
    """
    def __init__(
        self,
        env: gym.Env,
        image_shape: tuple[int, int] | None = None,
        pixels_transform: Callable[[np.ndarray], Any] | None = None,
        required_keys: Iterable[str] | None = None,
        image_resample: str | int | None = None,
        add_pixels: bool = False):
        super().__init__(env)
        required = list(required_keys or [])
        env = EverythingToInfoWrapper(env)
        if add_pixels:
            required.append(r'^pixels(?:\..*)?$')
            env = AddPixelsWrapper(env, image_shape, pixels_transform, image_resample)
        self.env = EnsureInfoKeysWrapper(env, required)
