"""RoboFactory tasks (multi-arm manipulation on ManiSkill) as stable-marl environments, with per-arm cameras and joint states."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/envs/robofactory/00_env.ipynb.

# %% ../../../nbs/envs/robofactory/00_env.ipynb #f627d7d2
from __future__ import annotations

import os
from typing import Any

import numpy as np
from gymnasium import spaces

from ..base import MultiAgentEnv
from ...types import AgentID

# %% auto #0
__all__ = ['TASKS', 'SCENES', 'ASSET_REPO', 'asset_dir', 'download_assets', 'RoboFactoryEnv']

# %% ../../../nbs/envs/robofactory/00_env.ipynb #7dce1055
TASKS = {   # task: (RoboFactory config file, number of arms)
    'LiftBarrier': ('lift_barrier', 2),
    'PassShoe': ('pass_shoe', 2),
    'PlaceFood': ('place_food', 2),
    'TwoRobotsStackCube': ('two_robots_stack_cube', 2),
    'CameraAlignment': ('camera_alignment', 3),
    'ThreeRobotsStackCube': ('three_robots_stack_cube', 3),
    'TakePhoto': ('take_photo', 4),
    'LongPipelineDelivery': ('long_pipeline_delivery', 4),
}
SCENES = ('table', 'robocasa')
ASSET_REPO = 'sparklexfantasy/RoboFactory_asset'   # RoboFactory's 3D assets (Hugging Face dataset)


def asset_dir() -> str:
    "Where RoboFactory's assets live: ``$ROBOFACTORY_ASSET_DIR``, else ``<cache_dir>/robofactory/assets``."
    return os.path.expanduser(os.environ.get('ROBOFACTORY_ASSET_DIR') or os.path.join(
        os.environ.get('STABLEMARL_HOME', '~/.stable_marl'), 'robofactory', 'assets'))


def download_assets(robocasa: bool = False) -> str:
    """
    Download RoboFactory's 3D assets (objects and table, 40 MB) to :func:`asset_dir`, and with
    `robocasa` ManiSkill's RoboCasa kitchens (for ``scene='robocasa'``, several GB, to ManiSkill's
    asset folder). Done automatically by the first `RoboFactoryEnv`; call it beforehand on machines
    without internet access at run time (e.g. HPC compute nodes).
    """
    from huggingface_hub import snapshot_download
    path = asset_dir()
    snapshot_download(repo_id=ASSET_REPO, repo_type='dataset', local_dir=path, ignore_patterns=['assets.zip'])
    if robocasa:
        import subprocess, sys
        subprocess.run([sys.executable, '-m', 'mani_skill.utils.download_asset', 'RoboCasa', '-y'], check=True)
    return path

# %% ../../../nbs/envs/robofactory/00_env.ipynb #74cf07d3
def _numpy(x) -> np.ndarray:
    "ManiSkill's batched tensors (one env) as numpy, without the batch dimension."
    return (x.detach().cpu().numpy() if hasattr(x, 'detach') else np.asarray(x))[0]


class RoboFactoryEnv(MultiAgentEnv):
    """
    The RoboFactory `task` (one of :data:`TASKS`) as a stable-marl env.

    Parameters
    ----------
    task : str
        RoboFactory task, e.g. 'LiftBarrier', 'TakePhoto'
    scene : str
        'table' (default) or 'robocasa' (a kitchen; needs ``download_assets(robocasa=True)``)
    observations : tuple
        Per-arm observations: 'pixels' (the arm's camera) and / or 'vector' (joint positions and velocities)
    camera_size : tuple, optional
        (height, width) of the arms' cameras; default RoboFactory's (240, 320)
    max_steps : int, optional
        Step limit (truncation); default the task's
    render_size : tuple
        (height, width) of :meth:`render`, the global camera
    reward_mode : str
        ManiSkill's reward: 'sparse' (1 on success) or 'none'
    shader : str
        ManiSkill's shader of the cameras: 'minimal' (fastest), 'default', 'rt' (ray tracing)
    """
    def __init__(self, task: str = 'LiftBarrier', scene: str = 'table', observations: tuple = ('pixels', 'vector'),
                 camera_size: tuple | None = None, max_steps: int | None = None, render_size: tuple = (240, 320),
                 reward_mode: str = 'sparse', shader: str = 'default', render_mode: str | None = 'rgb_array'):
        if task not in TASKS:
            raise ValueError(f"unknown RoboFactory task {task!r}: one of {list(TASKS)}")
        if scene not in SCENES:
            raise ValueError(f"unknown scene {scene!r}: one of {SCENES}")
        observations = tuple(observations)
        if not observations or set(observations) - {'pixels', 'vector'}:
            raise ValueError(f"observations: 'pixels' and / or 'vector', not {observations}")
        if not os.path.isdir(os.path.join(asset_dir(), 'objects')):
            print(f"Downloading RoboFactory's assets to {asset_dir()}")
            download_assets()
        import gymnasium as gym
        from stable_marl.envs.robofactory import upstream
        self.task, self.scene, self.observations = task, scene, observations
        self.num_agents = TASKS[task][1]
        self.render_mode = render_mode
        self.config = os.path.join(upstream.CONFIG_DIR, scene, f'{TASKS[task][0]}.yaml')
        cameras = dict(shader_pack=shader)
        if camera_size is not None:
            cameras.update(height=int(camera_size[0]), width=int(camera_size[1]))
        kwargs = dict(max_episode_steps=max_steps) if max_steps is not None else {}
        self._env = gym.make(f'{task}-rf', config=self.config, obs_mode='rgb' if 'pixels' in observations else 'state_dict',
                             control_mode='pd_joint_pos', reward_mode=reward_mode, render_mode='rgb_array',
                             sim_backend='cpu', sensor_configs=cameras,
                             human_render_camera_configs=dict(height=int(render_size[0]), width=int(render_size[1]),
                                                              shader_pack=shader), **kwargs)
        self.max_steps = getattr(self._env, '_max_episode_steps', None)    # ManiSkill's TimeLimitWrapper
        self.agent_names = list(self._env.unwrapped.action_space.keys())      # 'panda-0', 'panda-1', ...
        self._obs = self._last_info = None
        self._episode = 0
        self.observation_space = spaces.Dict({a: spaces.Dict(self._agent_space()) for a in range(self.num_agents)})
        self.action_space = spaces.Dict({a: spaces.Box(np.asarray(s.low, np.float32), np.asarray(s.high, np.float32), dtype=np.float32)
                                         for a, s in enumerate(self._env.unwrapped.action_space.values())})

    def _agent_space(self) -> dict:
        out = {}
        if 'pixels' in self.observations:
            cam = self._env.unwrapped.observation_space['sensor_data']['head_camera_agent0']['rgb']
            out['pixels'] = spaces.Box(0, 255, cam.shape[-3:], np.uint8)
        if 'vector' in self.observations:
            out['vector'] = spaces.Box(-np.inf, np.inf, (18,), np.float32)
        return out

    @property
    def state_space(self) -> spaces.Space:
        "ManiSkill's simulation state: poses and velocities of every object, joint states of every arm."
        return spaces.Box(-np.inf, np.inf, (int(self._env.unwrapped.get_state().shape[-1]),), np.float32)

    def state(self) -> np.ndarray:
        return _numpy(self._env.unwrapped.get_state()).astype(np.float32)

    def _observations(self, obs) -> dict[AgentID, dict]:
        out = {}
        for a, name in enumerate(self.agent_names):
            out[a] = {}
            if 'pixels' in self.observations:
                out[a]['pixels'] = _numpy(obs['sensor_data'][f'head_camera_agent{a}']['rgb'])
            if 'vector' in self.observations:
                joints = obs['agent'][name]
                out[a]['vector'] = np.concatenate([_numpy(joints['qpos']), _numpy(joints['qvel'])]).astype(np.float32)
        return out

    def _infos(self, info) -> dict[AgentID, dict]:
        success = bool(_numpy(info['success'])) if 'success' in info else False
        return {a: {'success': success} for a in range(self.num_agents)}

    def reset(self, seed: int | None = None, options: dict | None = None):
        """
        `options`: ``{'sim_state': state}`` starts from a recorded :meth:`state` (after the reset of `seed`).
        RoboFactory places the objects with numpy's global random generator, so it is seeded here too
        (and restored afterwards): a seed gives the same scene every time.
        """
        import torch
        super().reset(seed=seed)
        seed = int(self.np_random.integers(2 ** 31)) if seed is None else int(seed)
        rng_state = np.random.get_state()
        np.random.seed(seed)
        try:
            obs, info = self._env.reset(seed=seed)
        finally:
            np.random.set_state(rng_state)
        if options and options.get('sim_state') is not None:
            base = self._env.unwrapped
            base.set_state(torch.as_tensor(np.asarray(options['sim_state']), dtype=torch.float32)[None])
            obs, info = base.get_obs(), base.get_info()
        self._episode += 1
        self._seed = seed
        self._obs, self._last_info = obs, info
        return self._observations(obs), self._infos(info)

    def step(self, actions: dict[AgentID, Any]):
        act = {name: np.asarray(actions[a], np.float32).reshape(-1) for a, name in enumerate(self.agent_names)}
        obs, reward, terminated, truncated, info = self._env.step(act)
        self._obs, self._last_info = obs, info
        r, term, trunc = float(_numpy(reward)), bool(_numpy(terminated)), bool(_numpy(truncated))
        agents = range(self.num_agents)
        return (self._observations(obs), {a: r for a in agents}, {a: term for a in agents},
                {a: trunc for a in agents}, self._infos(info))

    def hold_action(self) -> np.ndarray:
        "Actions keeping every arm where it is, (num_agents, 8): its joint positions, the gripper's opening."
        out = []
        for agent in self._env.unwrapped.agent.agents:
            q = _numpy(agent.robot.get_qpos())
            low, high = -0.01, 0.04                              # pd_joint_pos's gripper range (Panda)
            out.append(np.r_[q[:7], 2 * (q[7] - low) / (high - low) - 1].astype(np.float32))
        return np.stack(out)

    def render(self) -> np.ndarray:
        "The global camera, (render_size, 3) uint8."
        return _numpy(self._env.render())

    def reset_options_from_dataset(self, init_row: dict, goal_row: dict) -> dict:
        "Reset options restoring the recorded step `init_row` (its ``state``); the goal is the task's success."
        return {'sim_state': np.asarray(init_row['state'])}

    def close(self):
        self._env.close()
