"""
RWARE's environment (`warehouse.py`), vendored from https://github.com/semitable/robotic-warehouse
(MIT, see LICENSE and README.md here). Not generated by nbdev; use it through :mod:`stable_marl.envs.rware`.
"""
