"""Steps several wrapped multi-agent envs together and stacks their info dicts."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/world/00_env_pool.ipynb.

# %% ../../nbs/world/00_env_pool.ipynb #16f38cd1
from __future__ import annotations

from typing import Any, Callable, Sequence

import gymnasium as gym
import numpy as np
from gymnasium import spaces
from gymnasium.vector.utils import batch_space

# %% auto #0
__all__ = ['joint_action_space', 'EnvPool', 'episode_done']

# %% ../../nbs/world/00_env_pool.ipynb #14b17eec
def joint_action_space(env: gym.Env) -> spaces.Space:
    """
    Action space of all the agents of `env` as one space: MultiDiscrete `(num_agents,)` if
    they are all Discrete, a Box `(num_agents, *shape)` if they are all Boxes of one shape.
    """
    agent_spaces = [env.action_space[a] for a in range(env.unwrapped.num_agents)]
    if all(isinstance(s, spaces.Discrete) for s in agent_spaces):
        return spaces.MultiDiscrete([s.n for s in agent_spaces], start=[s.start for s in agent_spaces])
    if all(isinstance(s, spaces.Box) for s in agent_spaces) and len({s.shape for s in agent_spaces}) == 1:
        return spaces.Box(low=np.stack([s.low for s in agent_spaces]), high=np.stack([s.high for s in agent_spaces]),
                          dtype=agent_spaces[0].dtype)
    return spaces.Tuple(agent_spaces)


class EnvPool:
    "Runs `num_envs` wrapped multi-agent envs side by side, one after the other in this process."
    def __init__(
        self,
        env_fns: Sequence[Callable[[], gym.Env]] # One factory per env, each called once; the envs must return flat info dicts (wrapped with `MegaWrapper`)
    ):
        self.envs: list[gym.Env] = [fn() for fn in env_fns]
        assert self.envs, "EnvPool needs at least one env"
        self.num_agents: int = self.envs[0].unwrapped.num_agents
        assert all(env.unwrapped.num_agents == self.num_agents for env in self.envs), \
            "All envs of a pool must have the same number of agents"
        self.seeds = np.full(self.num_envs, -1, dtype=np.int64)
        self._single_action_space = joint_action_space(self.envs[0])
        # cached: a batched space rebuilt on each access would never advance its RNG
        self._action_space = batch_space(self._single_action_space, self.num_envs)
        self._observation_space = None   # batched lazily (the per-agent views make it large)
        self._stacked_infos: dict[str, Any] | None = None

    @property
    def num_envs(self) -> int:
        return len(self.envs)

    @property
    def action_space(self) -> spaces.Space:
        "Batched action space: samples have shape (num_envs, num_agents)."
        return self._action_space

    @property
    def single_action_space(self) -> spaces.Space:
        "Joint action space of the agents of one env."
        return self._single_action_space

    @property
    def observation_space(self) -> spaces.Space:
        "Batched observation space (each leaf with a leading num_envs axis)."
        if self._observation_space is None:
            self._observation_space = batch_space(self.single_observation_space, self.num_envs)
        return self._observation_space

    @property
    def single_observation_space(self) -> spaces.Dict:
        "Observation space of one env (agent id -> agent observation space)."
        return self.envs[0].observation_space

    @property
    def state_space(self) -> spaces.Space:
        "Global state space of one env."
        return self.envs[0].unwrapped.state_space

    @property
    def variation_space(self):
        "Variation space of the envs, or None if they do not define one."
        return getattr(self.envs[0].unwrapped, 'variation_space', None)

    @property
    def single_variation_space(self):
        "Variation space of one env (alias of `variation_space`, as in stable-worldmodel)."
        return self.variation_space

    def close(self):
        for env in self.envs:
            env.close()

# %% ../../nbs/world/00_env_pool.ipynb #b3ae90b9
def _broadcast_arg(arg, n: int, increment: bool = False) -> list:
    "One value per env: lists are used as is, an int seed becomes `seed + i`, anything else is shared."
    if isinstance(arg, (list, tuple, np.ndarray)):
        assert len(arg) == n, f"Expected {n} values, got {len(arg)}"
        return list(arg)
    if increment and isinstance(arg, (int, np.integer)):
        return [int(arg) + i for i in range(n)]
    return [arg] * n


def _check_info(info: Any):
    if not isinstance(info, dict) or 'step_idx' not in info:
        raise TypeError("EnvPool envs must return flat info dicts: wrap them with MegaWrapper "
                        "(stable_marl.wrappers.default), as World does")


def _stack_fresh(per_env_infos: list[dict]) -> dict[str, Any]:
    "Stacked info buffers, (num_envs, 1, ...) for arrays and numbers, nested lists otherwise."
    stacked = {}
    for key in per_env_infos[0]:
        values = [info[key] for info in per_env_infos]
        if isinstance(values[0], (np.ndarray, np.generic, bool, int, float)) and not isinstance(values[0], str):
            stacked[key] = np.stack([np.asarray(v) for v in values])[:, None]
        else:
            stacked[key] = [[v] for v in values]
    return stacked


def _write_env_info(stacked: dict, i: int, info: dict):
    "Write the info of env `i` into the stacked buffers, in place."
    for key, value in info.items():
        if key in stacked:
            stacked[key][i][0] = value


def episode_done(terminateds: np.ndarray, truncateds: np.ndarray) -> np.ndarray:
    "Whether each env's episode is over (every agent terminated or truncated), shape (num_envs,)."
    return (np.asarray(terminateds) | np.asarray(truncateds)).all(axis=1)

# %% ../../nbs/world/00_env_pool.ipynb #ff185a6d
from fastcore.utils import patch

@patch
def reset(
    self: EnvPool,
    seed: int | Sequence[int | None] | None = None,
    options: dict | Sequence[dict | None] | None = None,
    mask: np.ndarray | None = None) -> tuple[None, dict]:
    "Reset the envs (only those where `mask` is True, if given) and return `(None, infos)`."
    seeds, options = _broadcast_arg(seed, self.num_envs, increment=True), _broadcast_arg(options, self.num_envs)
    per_env_infos = [None] * self.num_envs
    for i in (range(self.num_envs) if mask is None else np.flatnonzero(mask)):
        _, per_env_infos[i] = self.envs[i].reset(seed=seeds[i], options=options[i])
        _check_info(per_env_infos[i])
        self.seeds[i] = -1 if seeds[i] is None else seeds[i]
    if self._stacked_infos is None or mask is None:
        if any(info is None for info in per_env_infos):
            raise RuntimeError("The first reset of an EnvPool must reset every env")
        self._stacked_infos = _stack_fresh(per_env_infos)
    else:
        for i, info in enumerate(per_env_infos):
            if info is not None:
                _write_env_info(self._stacked_infos, i, info)
    return None, self._stacked_infos

@patch
def step(
    self: EnvPool,
    actions: np.ndarray,
    mask: np.ndarray | None = None) -> tuple[None, np.ndarray, np.ndarray, np.ndarray, dict]:
    """
    Step the envs (only those where `mask` is True, if given) with `actions` of shape
    `(num_envs, num_agents)`. Returns `(None, rewards, terminateds, truncateds, infos)`,
    the first three of shape `(num_envs, num_agents)`.
    """
    actions = np.asarray(actions)
    assert actions.shape[:2] == (self.num_envs, self.num_agents), \
        f"Expected actions of shape ({self.num_envs}, {self.num_agents}), got {actions.shape}"
    shape = (self.num_envs, self.num_agents)
    rewards, terminateds, truncateds = np.zeros(shape, np.float32), np.zeros(shape, bool), np.zeros(shape, bool)
    for i in (range(self.num_envs) if mask is None else np.flatnonzero(mask)):
        act = {a: actions[i, a].item() if actions[i, a].ndim == 0 else actions[i, a] for a in range(self.num_agents)}
        _, rew, term, trunc, info = self.envs[i].step(act)
        _write_env_info(self._stacked_infos, i, info)
        for a in range(self.num_agents):
            rewards[i, a], terminateds[i, a], truncateds[i, a] = rew[a], term[a], trunc[a]
    return None, rewards, terminateds, truncateds, self._stacked_infos
