"""Agents that communicate: comm-core's networks, with the agents of an environment as nodes."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/comm/00_core.ipynb.

# %% ../../nbs/comm/00_core.ipynb #0748963e
from __future__ import annotations

from typing import Any, Callable

import numpy as np

# %% auto #0
__all__ = ['node_id', 'agent_index', 'make_topology', 'message_bits', 'AgentNetwork']

# %% ../../nbs/comm/00_core.ipynb #b5f02a91
def _comm_core():
    "comm-core's building blocks, imported on first use."
    try:
        import comm_core as cc
        cc.Network, cc.DistanceTopology                      # networks and distance topologies: comm-core >= 44b7272
    except (ImportError, AttributeError) as e:
        if getattr(e, 'name', None) == 'comm_core':
            raise ModuleNotFoundError("stable_marl.comm needs comm-core: pip install 'stable-marl[comm]'") from e
        raise ImportError(f"stable_marl.comm needs a comm-core with networks and backends ({e})") from e
    return cc


def node_id(agent: int) -> str:
    "The comm-core node id of agent `agent`: 'agent_<agent>'."
    return f'agent_{int(agent)}'


def agent_index(node: str) -> int:
    "The agent index of a comm-core node id ('agent_3' -> 3)."
    return int(str(node).rsplit('_', 1)[1])


def make_topology(
    spec, # 'full_mesh', 'star' (around agent `center`), 'none' (no links), or a comm-core `Topology`
    num_agents: int, # Number of agents (nodes `agent_0 ..`)
    center: int = 0 # Center of the 'star' topology
):
    "A comm-core topology over the agents."
    cc = _comm_core()
    ids = [node_id(a) for a in range(num_agents)]
    if isinstance(spec, cc.Topology):
        return spec
    if spec == 'full_mesh':
        return cc.FullMeshTopology(ids)
    if spec == 'star':
        return cc.StarTopology(node_id(center), ids)
    if spec == 'none':
        return cc.GraphTopology([])
    raise ValueError(f"topology: 'full_mesh', 'star', 'none' or a comm-core Topology, not {spec!r}")


def message_bits(
    payload, # What is sent (anything numpy can turn into an array)
    bits_per_element: int | None = None # Bits per number (e.g. after quantization); default: the array's own dtype
) -> int: # Size in bits
    "Size of a message, for the channel and the metrics."
    arr = np.asarray(payload)
    return int(arr.size * bits_per_element) if bits_per_element else int(arr.nbytes * 8)

# %% ../../nbs/comm/00_core.ipynb #2dc6a1f7
class AgentNetwork:
    "A comm-core `Network` whose nodes are the agents of one environment."
    def __init__(
        self,
        num_agents: int, # Number of agents (nodes `agent_0 ..`)
        topology='full_mesh', # 'full_mesh', 'star', 'none' or a comm-core `Topology`
        channel=None, # A comm-core `Channel` (default: a perfect channel), used through an `AnalyticalBackend`
        backend=None, # A comm-core `CommunicationBackend` (instead of `channel`)
        protocol=None, # A comm-core `Protocol` (default `IdealProtocol`)
        center: int = 0, # Center of the 'star' topology
        bits_per_element: int | None = None, # Message size accounting (see `message_bits`)
        seed: int | None = None # Seed of the channel (see `reset`)
    ):
        cc = _comm_core()
        if channel is not None and backend is not None:
            raise ValueError("pass a channel or a backend, not both")
        self.num_agents, self.center, self.bits_per_element = int(num_agents), center, bits_per_element
        self.backend = backend if backend is not None else cc.AnalyticalBackend(channel if channel is not None else cc.IdentityChannel())
        self.topology = make_topology(topology, self.num_agents, center)
        self.network = cc.Network(nodes=[cc.Node(node_id(a)) for a in range(self.num_agents)], topology=self.topology,
                                  protocol=protocol if protocol is not None else cc.IdealProtocol(), backend=self.backend)
        self.last_results: list = []
        self.reset(seed)

    def reset(self, seed: int | None = None):
        "A new episode (comm-core's `Network.reset`: clock, queues, inboxes, metrics); `seed` reseeds the channel."
        self.network.reset(seed)
        self.last_results = []

    @property
    def metrics(self):
        "comm-core's metrics of the episode so far (transmissions, losses, bits, latency, energy)."
        return self.network.metrics.summary()

    def set_topology(self, topology):
        "Change who can talk to whom (e.g. agents that moved out of range)."
        self.topology = make_topology(topology, self.num_agents, self.center)
        self.network.topology = self.topology

    def neighbors(self, agent: int) -> list[int]:
        "The agents `agent` can send to."
        return sorted(agent_index(n) for n in self.topology.neighbors(node_id(agent)))

    def send(
        self,
        sender: int, # Agent sending
        receiver: int, # Agent it is sent to (must be a neighbour)
        payload: Any, # What is sent
        type: str = 'message', # comm-core's message type (e.g. 'latent', 'observation')
        size_bits: int | None = None, # Default: `message_bits(payload)`
        **metadata
    ):
        "Queue a message; it is transmitted at the next `step`."
        cc = _comm_core()
        size = message_bits(payload, self.bits_per_element) if size_bits is None else int(size_bits)
        self.network.send(cc.Message(sender=node_id(sender), receiver=node_id(receiver), payload=payload, type=type,
                                     timestamp=self.network.time, size_bits=size, metadata=metadata))

    def step(self, dt: float = 1.0) -> list:
        "Transmit what the protocol schedules; the comm-core `TransmissionResult`s."
        self.last_results = self.network.step(dt)
        return self.last_results

    def receive(self, agent: int) -> list:
        "The messages delivered to `agent` since the last call (comm-core `Message`s, as the channel delivered them)."
        return self.network.receive(node_id(agent))

    def exchange(
        self,
        payloads: dict[int, Any], # Each agent's payload (None: the agent sends nothing)
        type: str = 'message', # comm-core's message type
        dt: float = 1.0 # Time step of the network
    ) -> dict[int, dict[int, Any]]: # received[i][j]: what agent i received from agent j
        "One round: every agent sends its payload to each of its neighbours, then one network step."
        for a, payload in payloads.items():
            if payload is None:
                continue
            for b in self.neighbors(a):
                self.send(a, b, payload, type=type)
        self.step(dt)
        return {a: {agent_index(m.sender): m.payload for m in self.receive(a)} for a in range(self.num_agents)}
