"""Communication as part of an environment: each agent observes the messages that reached it through a comm-core network."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/comm/01_wrapper.ipynb.

# %% ../../nbs/comm/01_wrapper.ipynb #0250e27e
from __future__ import annotations

import copy
from typing import Any, Callable

import gymnasium as gym
import numpy as np
from gymnasium import spaces

from .core import AgentNetwork, _comm_core, message_bits, node_id

# %% auto #0
__all__ = ['multigrid_positions', 'within_range', 'CommunicationWrapper', 'communication']

# %% ../../nbs/comm/01_wrapper.ipynb #a109b13c
def multigrid_positions(env) -> np.ndarray:
    "Positions of the agents of a MultiGrid env, (num_agents, 2)."
    return np.array([agent.state.pos for agent in env.agents], np.float64)


def within_range(
    radius: float, # Largest distance at which two agents can communicate
    positions: Callable | None = None, # positions(env) -> (num_agents, d); default `multigrid_positions`
    ord: float = np.inf # Norm of the distance (inf: Chebyshev, i.e. squares on a grid; 2: Euclidean)
) -> Callable:
    "A topology recomputed at every step: links between the agents at most `radius` apart."
    positions = positions or multigrid_positions
    def topology(env):
        cc = _comm_core()
        pos = np.asarray(positions(env), np.float64)
        n = len(pos)
        return cc.GraphTopology([cc.Link(node_id(a), node_id(b)) for a in range(n) for b in range(n)
                                 if a != b and np.linalg.norm(pos[a] - pos[b], ord=ord) <= radius])
    return topology


class CommunicationWrapper(gym.Wrapper):
    "Agents exchange messages over a comm-core network at every step; what they received is in their observations."
    def __init__(
        self,
        env: gym.Env, # A stable-marl `MultiAgentEnv` (possibly wrapped)
        message_keys: tuple | None = None, # Observation keys each agent sends (flattened, concatenated)
        message_fn: Callable | None = None, # message_fn(env, agent, obs) -> array of `message_dim` numbers, or None
        message_dim: int | None = None, # Size of `message_fn`'s messages
        topology='full_mesh', # 'full_mesh', 'star', 'none', a comm-core `Topology`, or topology(env) at every step
        channel=None, # comm-core `Channel` (default: perfect)
        backend=None, # comm-core `CommunicationBackend` (instead of `channel`)
        protocol=None, # comm-core `Protocol` class / factory
        center: int = 0, # Center of the 'star' topology
        bits_per_element: int | None = None # Message size accounting (default: float32, 32 bits per number)
    ):
        super().__init__(env)
        if (message_keys is None) == (message_fn is None):
            raise ValueError("pass message_keys or message_fn")
        self.num_agents = env.unwrapped.num_agents
        agent_space = env.observation_space[0]
        if message_keys is not None:
            message_keys = tuple(message_keys)
            message_dim = sum(int(np.prod(agent_space[k].shape)) or 1 for k in message_keys)
        elif message_dim is None:
            raise ValueError("message_fn needs a message_dim")
        self.message_keys, self.message_fn, self.message_dim = message_keys, message_fn, int(message_dim)
        dynamic = callable(topology) and not isinstance(topology, (str, _comm_core().Topology))
        self._topology_fn = topology if dynamic else None
        self.comm = AgentNetwork(self.num_agents, 'none' if dynamic else topology, channel=channel, backend=backend,
                                 protocol=protocol, center=center, bits_per_element=bits_per_element)
        A, D = self.num_agents, self.message_dim
        self.observation_space = spaces.Dict({a: spaces.Dict({
            **env.observation_space[a].spaces,
            'messages': spaces.Box(-np.inf, np.inf, (A, D), np.float32),
            'message_mask': spaces.MultiBinary(A)}) for a in range(A)})

    def _message(self, agent: int, obs: dict):
        if self.message_keys is not None:
            return np.concatenate([np.asarray(obs[agent][k], np.float32).reshape(-1) for k in self.message_keys])
        m = self.message_fn(self.env.unwrapped, agent, obs)
        if m is None:
            return None
        m = np.asarray(m, np.float32).reshape(-1)
        if m.size != self.message_dim:
            raise ValueError(f"message_fn returned {m.size} numbers for agent {agent}, message_dim is {self.message_dim}")
        return m

    def _communicate(self, obs: dict, infos: dict):
        if self._topology_fn is not None:
            self.comm.set_topology(self._topology_fn(self.env.unwrapped))
        payloads = {a: self._message(a, obs) for a in range(self.num_agents)}
        received = self.comm.exchange(payloads)
        sent = {a: 0 for a in range(self.num_agents)}
        for r in self.comm.last_results:
            sent[int(r.transmission.sender.rsplit('_', 1)[1])] += r.size_bits
        A, D = self.num_agents, self.message_dim
        obs, infos = dict(obs), dict(infos)
        for a in range(A):
            messages, mask = np.zeros((A, D), np.float32), np.zeros(A, bool)
            for j, payload in received[a].items():
                messages[j], mask[j] = np.asarray(payload, np.float32).reshape(-1), True
            obs[a] = {**obs[a], 'messages': messages, 'message_mask': mask}
            infos[a] = {**infos.get(a, {}), 'comm_bits_sent': np.int64(sent[a]), 'comm_received': np.int64(mask.sum())}
        return obs, infos

    def reset(self, *, seed: int | None = None, options: dict | None = None):
        "Reset the env and the network (seeded with the env's `seed`); the first round of messages."
        obs, infos = self.env.reset(seed=seed, options=options)
        self.comm.reset(seed)
        return self._communicate(obs, infos)

    def step(self, actions):
        "Step the env, then one round of messages."
        obs, rewards, terminations, truncations, infos = self.env.step(actions)
        obs, infos = self._communicate(obs, infos)
        return obs, rewards, terminations, truncations, infos

    @property
    def metrics(self):
        "comm-core's metrics of the episode so far."
        return self.comm.metrics


def communication(**kwargs) -> Callable:
    """
    A `World` pre-wrapper adding a `CommunicationWrapper` (`kwargs`) to every env, each with its own copy of the
    channel / backend: `World(..., pre_wrappers=[communication(message_keys=('position',), channel=...)])`.
    """
    return lambda env: CommunicationWrapper(env, **copy.deepcopy(kwargs))
