__version__ = "0.0.1"
"""The public API: environments, the `World` that runs policies in them, and the datasets it collects."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_init.ipynb.

# %% auto #0
__all__ = ['MultiAgentEnv', 'make', 'list_envs', 'register', 'World', 'EnvPool', 'Policy', 'ExpertPolicy', 'RandomPolicy',
           'TrajectoryDataset', 'load_episodes']

# %% ../nbs/00_init.ipynb #dd2d93d0
from .envs import MultiAgentEnv, make, list_envs, register
from .world import World, EnvPool
from .policy import Policy, ExpertPolicy, RandomPolicy
from .data import TrajectoryDataset, load_episodes

_all_ = ['MultiAgentEnv', 'make', 'list_envs', 'register', 'World', 'EnvPool',
         'Policy', 'ExpertPolicy', 'RandomPolicy', 'TrajectoryDataset', 'load_episodes']
