__version__ = "0.0.1"
"""The public API: create any registered environment with `make`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_init.ipynb.

# %% auto #0
__all__ = ['MultiAgentEnv', 'make', 'list_envs', 'register']

# %% ../nbs/00_init.ipynb #dd2d93d0
from .envs import MultiAgentEnv, make, list_envs, register

_all_ = ['MultiAgentEnv', 'make', 'list_envs', 'register']
