"""Every policy type a `World` can run, with the interface of stable-worldmodel."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_policy.ipynb.

# %% ../nbs/02_policy.ipynb #07a02e32
from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from typing import Any, Callable

import numpy as np

from .envs.base import MultiAgentEnv
from .protocols import Actionable, Transformable

# %% auto #0
__all__ = ['Policy', 'BasePolicy', 'RandomPolicy', 'ExpertPolicy', 'FeedForwardPolicy', 'PlanConfig', 'WorldModelPolicy']

# %% ../nbs/02_policy.ipynb #b086ed28
class BasePolicy:
    """
    Base class of the policies a :class:`World` runs.

    Attributes
    ----------
    env : EnvPool
        The pool of envs the policy acts in (set by :meth:`set_env`)
    type : str
        Identifier of the policy type
    """
    env: Any
    type: str

    def __init__(self, **kwargs: Any):
        self.env = None
        self.type = 'base'
        for arg, value in kwargs.items():
            setattr(self, arg, value)

    def get_action(self, info_dict: dict, **kwargs: Any) -> np.ndarray:
        "Actions of shape (num_envs, num_agents) for the stacked `info_dict`."
        raise NotImplementedError

    def set_env(self, env: Any):
        "Attach the pool of envs this policy acts in."
        self.env = env

    def _prepare_info(self, info_dict: dict) -> dict:
        """
        A copy of `info_dict` ready for a torch model:

        * ``self.process[key]`` (a scaler with ``transform``, e.g. from sklearn) is applied to
          the features of `key`, i.e. its last axis
        * ``self.transform[key]`` (a callable on a batch of channel-first images) is applied to
          the images of `key`, of shape (..., H, W, C): it gets them as (N, C, H, W), and the
          result is reshaped back to (..., C', H', W')
        * numeric numpy arrays become torch tensors
        """
        import torch
        process, transform = getattr(self, 'process', {}), getattr(self, 'transform', {})
        out = {}
        for key, value in info_dict.items():
            if key in process:
                value = np.asarray(value)
                value = process[key].transform(value.reshape(-1, value.shape[-1])).reshape(value.shape)
            if key in transform:
                value = torch.as_tensor(value)
                images = value.reshape(-1, *value.shape[-3:]).permute(0, 3, 1, 2)
                images = transform[key](images)
                value = images.reshape(*value.shape[:-3], *images.shape[1:])
            if isinstance(value, np.ndarray) and value.dtype.kind not in 'USO':
                value = torch.from_numpy(value)
            out[key] = value
        return out

# %% ../nbs/02_policy.ipynb #be7c2d86
class RandomPolicy(BasePolicy):
    "Samples uniformly random actions from the pool's batched action space."
    def __init__(self, seed: int | None = None, **kwargs: Any):
        """
        `seed` seeds the action space when the policy is attached to a pool,
        making the sampled actions reproducible.
        """
        super().__init__(**kwargs)
        self.type = 'random'
        self.seed = seed

    def get_action(self, info_dict: dict, **kwargs: Any) -> np.ndarray:
        return self.env.action_space.sample()

    def set_env(self, env: Any):
        super().set_env(env)
        if self.seed is not None:
            self._set_seed(self.seed)

    def _set_seed(self, seed: int):
        if self.env is not None:
            self.env.action_space.seed(seed)

# %% ../nbs/02_policy.ipynb #45f79b02
class ExpertPolicy(BasePolicy):
    """
    Base class of privileged (scripted) policies, which read the true state of each env
    instead of the info dict, e.g. a shortest-path planner to collect expert datasets.

    Subclasses implement :meth:`act`, the actions of all the agents of one env.
    """
    def __init__(self, **kwargs: Any):
        super().__init__(**kwargs)
        self.type = 'expert'

    def get_action(self, info_dict: dict, **kwargs: Any) -> np.ndarray:
        return np.array([self.act(env.unwrapped) for env in self.env.envs])

    def act(self, env: MultiAgentEnv) -> np.ndarray:
        "Actions of the agents of `env`, of shape (num_agents,)."
        raise NotImplementedError

# %% ../nbs/02_policy.ipynb #92de0f32
class FeedForwardPolicy(BasePolicy):
    """
    Computes actions with one forward pass of a torch model, e.g. a behaviour-cloned policy or
    a trained MARL actor.

    ``model.get_action(info_dict)`` receives the prepared info dict (see
    :meth:`BasePolicy._prepare_info`), with its tensors on the model's device, and returns
    actions of shape (num_envs, num_agents). ``process['action']``, if given, maps them back
    with its ``inverse_transform``.
    """
    def __init__(
        self,
        model: Actionable,
        process: dict[str, Transformable] | None = None,
        transform: dict[str, Callable] | None = None,
        **kwargs: Any):
        if not isinstance(model, Actionable):
            raise TypeError(f"FeedForwardPolicy needs a model with `get_action` (Actionable), got {type(model).__name__}")
        super().__init__(**kwargs)
        self.type = 'feed_forward'
        self.model = model.eval()
        self.process = process or {}
        self.transform = transform or {}

    def get_action(self, info_dict: dict, **kwargs: Any) -> np.ndarray:
        import torch
        info = self._prepare_info(info_dict)
        parameter = next(self.model.parameters(), None)
        if parameter is not None:
            info = {k: v.to(parameter.device) if torch.is_tensor(v) else v for k, v in info.items()}
        with torch.no_grad():
            action = self.model.get_action(info)
        if torch.is_tensor(action):
            action = action.cpu().numpy()
        if 'action' in self.process:
            action = self.process['action'].inverse_transform(action)
        return action

# %% ../nbs/02_policy.ipynb #b71fb7df
@dataclass(frozen=True)
class PlanConfig:
    """
    Configuration of the model-predictive control loop of a :class:`WorldModelPolicy`
    (same fields as stable-worldmodel).

    Attributes
    ----------
    horizon : int
        Planning horizon, in steps
    receding_horizon : int
        Steps of each plan executed before replanning
    history_len : int
        Context steps given to the world model (only 1 is supported for now)
    history_max_len : int, optional
        Capacity of the context buffer
    action_block : int
        Times each action is repeated (only 1 is supported for now)
    warm_start : bool
        Whether the rest of the previous plan is passed to the solver
    """
    horizon: int
    receding_horizon: int
    history_len: int = 1
    history_max_len: int | None = None
    action_block: int = 1
    warm_start: bool = True

    def __post_init__(self):
        if self.history_len < 1:
            raise ValueError(f"history_len must be >= 1, got {self.history_len}")
        if not 1 <= self.receding_horizon <= self.horizon:
            raise ValueError(f"receding_horizon must be in [1, horizon], got {self.receding_horizon}")

    @property
    def plan_len(self) -> int:
        "Length of a plan, in env steps."
        return self.horizon * self.action_block

# %% ../nbs/02_policy.ipynb #f42df439
class WorldModelPolicy(BasePolicy):
    """
    Model-predictive control: plans the actions of all agents with a solver (e.g. a
    :class:`CategoricalCEMSolver` over a world model), executes the first ``receding_horizon``
    steps of the plan, then replans. Each env replans on its own schedule, and from scratch when
    it starts a new episode (``_needs_flush``).

    Centralised or decentralised planning is chosen by the solver's ``mode`` and the objective
    (joint or per-agent cost).
    """
    def __init__(
        self,
        solver: Any,
        config: PlanConfig,
        process: dict[str, Transformable] | None = None,
        transform: dict[str, Callable] | None = None,
        history_keys: tuple[str, ...] = ('pov',),
        **kwargs: Any):
        super().__init__(**kwargs)
        self.type = 'world_model'
        self.cfg, self.solver = config, solver
        self.process, self.transform = process or {}, transform or {}
        self.history_keys = tuple(history_keys)
        self._action_buffer: list[deque] | None = None
        self._next_init = None

    @property
    def flatten_receding_horizon(self) -> int:
        "Executed steps of a plan, in env steps."
        return self.cfg.receding_horizon * self.cfg.action_block

    def set_env(self, env: Any):
        from stable_marl.planning.solver import Solver
        if self.cfg.history_len != 1 or self.cfg.action_block != 1:
            raise NotImplementedError("WorldModelPolicy supports history_len=1 and action_block=1 for now")
        self.env = env
        self.solver.configure(action_space=env.single_action_space, n_envs=env.num_envs, config=self.cfg)
        if not isinstance(self.solver, Solver):   # checked once configured, as its properties need the config
            raise TypeError("The solver must implement the Solver protocol")
        self._action_buffer = [deque(maxlen=self.flatten_receding_horizon) for _ in range(env.num_envs)]
        self._next_init = None

    def get_action(self, info_dict: dict, **kwargs: Any) -> np.ndarray:
        import torch
        n_envs, A = self.env.num_envs, self.env.num_agents
        needs_flush = info_dict.pop('_needs_flush', None)
        if needs_flush is not None:
            for i in np.flatnonzero(needs_flush):
                self._action_buffer[i].clear()
                if self._next_init is not None:
                    self._next_init[i] = 0
        info = self._prepare_info(info_dict)

        terminated = info.get('terminated')
        dead = (np.asarray(terminated).reshape(n_envs, -1).all(axis=1) if terminated is not None
                else np.zeros(n_envs, bool))
        replan = [i for i in range(n_envs) if not self._action_buffer[i] and not dead[i]]
        if replan:
            idx = torch.as_tensor(replan, dtype=torch.long)
            sliced = {k: v[idx] if torch.is_tensor(v) else v[replan] if isinstance(v, np.ndarray)
                      else [v[i] for i in replan] if isinstance(v, list) else v
                      for k, v in info.items()}
            init = self._next_init[idx] if self._next_init is not None else None
            actions = self.solver(sliced, init_action=init)['actions']          # (n, horizon, A)
            keep = self.cfg.receding_horizon
            plan, rest = actions[:, :keep], actions[:, keep:]
            if self.cfg.warm_start and rest.shape[1] > 0:
                if self._next_init is None:
                    self._next_init = torch.zeros(n_envs, *rest.shape[1:], dtype=rest.dtype)
                self._next_init[idx] = rest
            elif not self.cfg.warm_start:
                self._next_init = None
            for row, i in enumerate(replan):
                self._action_buffer[i].extend(plan[row].reshape(self.flatten_receding_horizon, A))

        action = np.zeros((n_envs, A), dtype=np.int64)
        for i in range(n_envs):
            if not dead[i]:
                action[i] = np.asarray(self._action_buffer[i].popleft())
        if 'action' in self.process:
            action = self.process['action'].inverse_transform(action)
        return action


Policy = BasePolicy   # alias, as in stable-worldmodel
