"""Type aliases shared by every stable-marl module."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_types.ipynb.

# %% auto #0
__all__ = ['AgentID', 'ObsType', 'ActType', 'AgentDict']

# %% ../nbs/01_types.ipynb #385d448d
from typing import Any, TypeVar

_T = TypeVar('_T')

AgentID = int                       # agents are identified by their index, 0 .. num_agents - 1
ObsType = dict[str, Any]            # observation of a single agent
ActType = int                       # action of a single agent
AgentDict = dict[AgentID, _T]       # one value per agent, e.g. `AgentDict[ObsType]`
