"""In-memory episode storage that is both a `Writer` (fill it with `World.collect`) and a `Dataset` (train on it), as in stable-worldmodel."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/data/05_buffer.ipynb.

# %% ../../nbs/data/05_buffer.ipynb #2b89de47
# Adapted from stable-worldmodel's data package (https://github.com/galilai-group/stable-worldmodel):
#
# MIT License
#
# Copyright (c) 2026 GalilAI-group
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from __future__ import annotations

import logging
from collections import deque
from pathlib import Path
from typing import Any, Callable, Iterable

import numpy as np

from .dataset import Dataset
from .format import EPISODE_DATA_KEY, get_format, split_episode_data

Sampler = Callable[[int, 'ReplayBuffer', int, int], Any]

# %% auto #0
__all__ = ['Sampler', 'ReplayBuffer', 'classic_filter']

# %% ../../nbs/data/05_buffer.ipynb #b58343f6
def _uniform_sampler(step: int, buffer: ReplayBuffer, batch_size: int, history_len: int) -> np.ndarray:
    n = buffer.num_valid_ends(history_len)
    if n == 0:
        raise RuntimeError(f"ReplayBuffer.sample: no clips of history_len={history_len} available "
                           f"(num_episodes={buffer.num_episodes}, num_steps_stored={buffer.num_steps_stored})")
    return np.random.randint(0, n, size=batch_size)


class ReplayBuffer(Dataset):
    """
    In-memory ring-storage replay buffer.

    Parameters
    ----------
    max_steps : int
        Capacity in steps; whole episodes are evicted oldest first when a new one would not fit
    history_len : int
        Steps per clip of ``__getitem__`` (the Dataset's ``num_steps``) and default of :meth:`sample`
    frameskip : int
        Stride between the steps of a clip; ``action`` keeps every step, reshaped to
        ``(history_len, frameskip * action_dim)``
    sampler : callable, optional
        ``fn(step, buffer, batch_size, history_len) -> indices`` in ``[0, buffer.num_valid_ends(history_len))``
        (default: uniform)
    transform : callable, optional
        Dict-in / dict-out transform applied to each clip of ``__getitem__``
    key_filter : callable, optional
        ``fn(ep_data) -> ep_data`` choosing the columns stored (e.g. :func:`classic_filter`)
    """
    def __init__(
        self,
        max_steps: int,
        history_len: int = 1,
        frameskip: int = 1,
        sampler: Sampler | None = None,
        transform: Callable[[dict], dict] | None = None,
        key_filter: Callable[[dict], dict] | None = None):
        for name, value in (('max_steps', max_steps), ('history_len', history_len), ('frameskip', frameskip)):
            if value <= 0:
                raise ValueError(f"{name} must be positive, got {value}")
        self.max_steps, self.history_len, self.frameskip = int(max_steps), int(history_len), int(frameskip)
        self.num_steps = self.history_len
        self.span = self.num_steps * self.frameskip
        self.transform, self.key_filter = transform, key_filter
        self.sampler: Sampler = sampler if sampler is not None else _uniform_sampler
        self.metadata: dict[str, Any] = {}
        self._cols: dict[str, np.ndarray] = {}
        self._head = self._size = 0
        self._episodes: deque[tuple[int, int]] = deque()       # (ring start, length)
        self._episode_meta: deque[dict] = deque()              # episode-scoped data, aligned with _episodes
        self._sample_step = 0
        self._clip_starts: np.ndarray | None = None
        self._clip_starts_span: int | None = None

    # ---- Writer
    def __enter__(self) -> ReplayBuffer:
        return self

    def __exit__(self, *exc) -> None:
        return None

    def write_episode(self, ep_data: dict) -> None:
        "Append one finished episode (every column spanning the whole episode)."
        if not ep_data:
            return
        ep_data, episode_data = split_episode_data(ep_data)
        if self.key_filter is not None:
            ep_data = self.key_filter(ep_data)
        if not ep_data:
            return
        per_step, ep_len = self._coerce_episode(ep_data)
        if ep_len == 0:
            return
        if ep_len > self.max_steps:
            raise ValueError(f"ReplayBuffer.write_episode: episode length {ep_len} exceeds max_steps={self.max_steps}")
        self._ensure_allocated(per_step)
        self._evict_to_fit(ep_len)
        self._append(per_step, ep_len, episode_data)

    def write_episodes(self, episodes: Iterable[dict]) -> None:
        for ep in episodes:
            self.write_episode(ep)

    # ---- contents
    @property
    def column_names(self) -> list[str]:
        return list(self._cols)

    @property
    def episode_column_names(self) -> list[str]:
        seen, cols = set(), []
        for extra in self._episode_meta:
            for k in extra:
                if k not in seen:
                    seen.add(k); cols.append(k)
        return cols

    def get_episode_data(self, episodes_idx: np.ndarray | list[int] | None = None) -> dict[str, list]:
        cols = self.episode_column_names
        if not cols:
            return {}
        metas = list(self._episode_meta)
        idxs = range(len(metas)) if episodes_idx is None else [int(i) for i in np.asarray(episodes_idx, dtype=np.int64).reshape(-1)]
        return {k: [metas[i].get(k) for i in idxs] for k in cols}

    @property
    def num_episodes(self) -> int:
        return len(self._episodes)

    @property
    def num_steps_stored(self) -> int:
        return self._size

    @property
    def lengths(self) -> np.ndarray:
        return np.asarray([ln for _, ln in self._episodes], dtype=np.int32)

    @property
    def offsets(self) -> np.ndarray:
        lens = self.lengths
        if len(lens) == 0:
            return np.zeros(0, dtype=np.int64)
        return np.concatenate(([0], np.cumsum(lens[:-1]))).astype(np.int64)

    @property
    def clip_indices(self) -> list[tuple[int, int]]:
        "``(episode, start)`` of every clip of ``__getitem__``, in order (as :class:`Dataset`)."
        return [(ep, start) for ep, (_, ln) in enumerate(self._episodes) for start in range(max(0, ln - self.span + 1))]

    def num_valid_ends(self, history_len: int | None = None) -> int:
        "Number of clips of `history_len` steps (the index space the sampler draws from)."
        h = self.history_len if history_len is None else history_len
        return int(self._get_clip_starts(h * self.frameskip)[-1])

    # ---- sampling
    def sample(self, batch_size: int, history_len: int | None = None, step: int | None = None) -> dict[str, np.ndarray]:
        """
        A batch of clips drawn by the sampler: ``{column: (batch_size, history_len, ...)}`` numpy
        arrays (``transform`` is not applied). `step` is passed to the sampler (default: a counter
        of the calls).
        """
        if batch_size <= 0:
            raise ValueError(f"batch_size must be positive, got {batch_size}")
        h = self.history_len if history_len is None else history_len
        if h <= 0:
            raise ValueError(f"history_len must be positive, got {h}")
        flat = self._call_sampler(self._consume_step(step), batch_size, h)
        ep_idx, local_start = self._flat_to_clip(flat, h * self.frameskip)
        episodes = list(self._episodes)
        clips = [self._gather_clip(episodes[int(e)][0], int(s), h) for e, s in zip(ep_idx, local_start)]
        return {col: np.stack([c[col] for c in clips], axis=0) for col in self._cols}

    # ---- Dataset
    def __len__(self) -> int:
        return self.num_valid_ends(self.history_len)

    def __repr__(self) -> str:
        return (f"ReplayBuffer(episodes={self.num_episodes}, steps={self.num_steps_stored}/{self.max_steps}, "
                f"history_len={self.history_len}, frameskip={self.frameskip}, columns=[{', '.join(self.column_names) or '-'}])")

    def __getitem__(self, idx: int) -> dict:
        n = len(self)
        if n == 0:
            raise IndexError("ReplayBuffer is empty")
        if idx < 0:
            idx += n
        if not 0 <= idx < n:
            raise IndexError(idx)
        ep_idx, local_start = self._flat_to_clip(np.array([idx], dtype=np.int64), self.span)
        ring_start, _ = self._episodes[int(ep_idx[0])]
        clip = self._gather_clip(ring_start, int(local_start[0]), self.history_len)
        return self.transform(clip) if self.transform is not None else clip

    def _load_slice(self, ep_idx: int, start: int, end: int) -> dict:
        if not 0 <= ep_idx < self.num_episodes:
            raise IndexError(ep_idx)
        ring_start, ep_len = self._episodes[ep_idx]
        if not 0 <= start <= end <= ep_len:
            raise IndexError(f"slice [{start}:{end}] out of episode of length {ep_len}")
        positions = (ring_start + np.arange(start, end)) % self.max_steps
        return {col: arr[positions] for col, arr in self._cols.items()}

    def get_col_data(self, col: str) -> np.ndarray:
        "The whole column, episodes oldest first."
        return np.concatenate([self._cols[col][(start + np.arange(ln)) % self.max_steps] for start, ln in self._episodes]) \
            if self._episodes else self._cols[col][:0]

    # ---- export
    def episodes(self) -> Iterable[dict]:
        """
        The stored episodes as ``{column: [row, ...]}`` (what ``World.collect`` writes and every
        :class:`Writer` takes), with their episode-scoped data under ``EPISODE_DATA_KEY``.
        """
        for (ring_start, ep_len), extra in zip(list(self._episodes), list(self._episode_meta)):
            positions = (ring_start + np.arange(ep_len)) % self.max_steps
            ep = {col: list(arr[positions]) for col, arr in self._cols.items()}
            if extra:
                ep[EPISODE_DATA_KEY] = dict(extra)
            yield ep

    def dump(self, path: str | Path, format: str, mode: str = 'overwrite', **kwargs: Any) -> None:
        """
        Save the contents with the writer of `format` (`kwargs` go to it), with ``metadata``.
        Episode-scoped data is dropped, with a warning, if the format does not store it.
        """
        fmt = get_format(format)
        episodes: Iterable[dict] = self.episodes()
        if any(self._episode_meta) and not getattr(fmt, 'supports_episode_data', False):
            logging.warning("ReplayBuffer.dump: format '%s' does not support episode data; dropping it (columns %s).",
                            format, self.episode_column_names)
            episodes = ({k: v for k, v in ep.items() if k != EPISODE_DATA_KEY} for ep in episodes)
        with fmt.open_writer(path, mode=mode, **kwargs) as writer:
            if hasattr(writer, 'metadata'):
                writer.metadata.update(self.metadata)
            writer.write_episodes(episodes)

    def clear(self) -> None:
        "Drop every episode (the allocated arrays are reused)."
        self._head = self._size = 0
        self._episodes.clear()
        self._episode_meta.clear()
        self._invalidate_clip_cache()

    # ---- internals
    def _coerce_episode(self, ep_data: dict) -> tuple[dict[str, np.ndarray], int]:
        per_step, ep_len = {}, None
        for col, vals in ep_data.items():
            arr = np.asarray(vals)
            if arr.ndim == 0:
                raise ValueError(f"ReplayBuffer.write_episode: column '{col}' is scalar; expected a per-step array")
            if ep_len is None:
                ep_len = arr.shape[0]
            elif arr.shape[0] != ep_len:
                raise ValueError(f"ReplayBuffer.write_episode: column '{col}' has length {arr.shape[0]}, expected {ep_len}")
            per_step[col] = arr
        return per_step, ep_len or 0

    def _ensure_allocated(self, per_step: dict[str, np.ndarray]) -> None:
        if not self._cols:
            for col, arr in per_step.items():
                self._cols[col] = np.empty((self.max_steps, *arr.shape[1:]), dtype=arr.dtype)
            return
        existing, incoming = set(self._cols), set(per_step)
        if existing != incoming:
            raise ValueError(f"ReplayBuffer.write_episode: schema mismatch. missing={sorted(existing - incoming)}, "
                             f"extra={sorted(incoming - existing)}")
        for col, arr in per_step.items():
            if arr.shape[1:] != self._cols[col].shape[1:]:
                raise ValueError(f"ReplayBuffer.write_episode: column '{col}' per-step shape {arr.shape[1:]} "
                                 f"mismatches expected {self._cols[col].shape[1:]}")

    def _evict_to_fit(self, ep_len: int) -> None:
        evicted = False
        while self._size + ep_len > self.max_steps and self._episodes:
            _, n = self._episodes.popleft()
            self._episode_meta.popleft()
            self._size -= n
            evicted = True
        if evicted:
            self._invalidate_clip_cache()

    def _append(self, per_step: dict[str, np.ndarray], ep_len: int, episode_data: dict | None = None) -> None:
        positions = (self._head + np.arange(ep_len)) % self.max_steps
        for col, arr in per_step.items():
            self._cols[col][positions] = arr
        self._episodes.append((self._head, ep_len))
        self._episode_meta.append(dict(episode_data or {}))
        self._head = (self._head + ep_len) % self.max_steps
        self._size += ep_len
        self._invalidate_clip_cache()

    def _consume_step(self, step: int | None) -> int:
        if step is not None:
            return int(step)
        cur, self._sample_step = self._sample_step, self._sample_step + 1
        return cur

    def _call_sampler(self, step: int, batch_size: int, history_len: int) -> np.ndarray:
        flat = np.asarray(self.sampler(step, self, batch_size, history_len))
        if flat.shape != (batch_size,):
            raise ValueError(f"ReplayBuffer.sample: sampler returned shape {flat.shape}, expected ({batch_size},)")
        return flat.astype(np.int64, copy=False)

    def _flat_to_clip(self, flat: np.ndarray, span: int) -> tuple[np.ndarray, np.ndarray]:
        "Flat clip indices -> ``(episode index, clip start in the episode)``."
        starts = self._get_clip_starts(span)
        total = int(starts[-1])
        if flat.size and (flat.min() < 0 or flat.max() >= total):
            raise IndexError(f"ReplayBuffer: clip index out of range [0, {total})")
        ep_idx = np.searchsorted(starts[1:], flat, side='right')
        return ep_idx, flat - starts[ep_idx]

    def _get_clip_starts(self, span: int) -> np.ndarray:
        "Cumulative clip counts per episode, ``(N + 1,)``, cached per `span` until the episodes change."
        if self._clip_starts is None or self._clip_starts_span != span:
            n = len(self._episodes)
            valid = np.fromiter((max(0, ln - span + 1) for _, ln in self._episodes), dtype=np.int64, count=n)
            self._clip_starts = np.empty(n + 1, dtype=np.int64)
            self._clip_starts[0] = 0
            np.cumsum(valid, out=self._clip_starts[1:])
            self._clip_starts_span = span
        return self._clip_starts

    def _invalidate_clip_cache(self) -> None:
        self._clip_starts = self._clip_starts_span = None

    def _gather_clip(self, ring_start: int, clip_local_start: int, history_len: int) -> dict[str, np.ndarray]:
        "One clip: columns every `frameskip` steps, ``action`` dense, reshaped to ``(history_len, -1)``."
        base = ring_start + clip_local_start
        obs_idx = (base + np.arange(history_len) * self.frameskip) % self.max_steps
        action_idx = obs_idx if self.frameskip == 1 else (base + np.arange(history_len * self.frameskip)) % self.max_steps
        clip = {col: arr[action_idx if col == 'action' else obs_idx] for col, arr in self._cols.items()}
        if 'action' in clip:
            clip['action'] = clip['action'].reshape(history_len, -1)
        return clip


def classic_filter(ep_data: dict) -> dict:
    """
    ``key_filter`` keeping the classic replay-buffer columns: ``pixels`` (each agent's view),
    ``action``, ``reward``, ``terminated`` and ``truncated``.
    """
    classic_keys = ('pixels', 'action', 'reward', 'terminated', 'truncated')
    return {k: v for k, v in ep_data.items() if k in classic_keys}
