"""A registry of on-disk dataset formats, each with a streaming writer and a reader."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/data/00_format.ipynb.

# %% ../../nbs/data/00_format.ipynb #8c32003f
from __future__ import annotations

from pathlib import Path
from typing import Iterable, Protocol, runtime_checkable

# %% auto #0
__all__ = ['FORMATS', 'WRITE_MODES', 'validate_write_mode', 'register_format', 'list_formats', 'get_format', 'detect_format',
           'Format', 'Writer']

# %% ../../nbs/data/00_format.ipynb #9d60b5de
FORMATS: dict[str, type[Format]] = {}

WRITE_MODES = ('append', 'overwrite', 'error')
"""
Writer modes shared by all formats: ``append`` extends an existing dataset (default),
``overwrite`` replaces it, ``error`` raises :class:`FileExistsError` if it exists.
"""


def validate_write_mode(mode: str) -> str:
    if mode not in WRITE_MODES:
        raise ValueError(f"write mode must be one of {WRITE_MODES}, got {mode!r}")
    return mode


def register_format(cls: type[Format]) -> type[Format]:
    "Class decorator registering a :class:`Format` under its `name`."
    name = getattr(cls, 'name', None)
    if not name:
        raise ValueError(f"{cls.__name__} must set a non-empty `name` class attribute")
    if name in FORMATS and FORMATS[name].__qualname__ != cls.__qualname__:   # same class re-defined: replace
        raise ValueError(f"format {name!r} is already registered")
    FORMATS[name] = cls
    return cls


def list_formats() -> list[str]:
    return list(FORMATS)


def get_format(name: str) -> type[Format]:
    try:
        return FORMATS[name]
    except KeyError:
        raise ValueError(f"unknown format {name!r}; available: {list_formats()}") from None


def detect_format(path: str | Path) -> type[Format] | None:
    "The first registered format whose ``detect`` matches `path`, else None."
    for fmt in FORMATS.values():
        if fmt.detect(path):
            return fmt
    return None


class Format:
    "An on-disk dataset format: subclasses set `name`, implement `detect` and their reader / writer."
    name: str = ''

    @classmethod
    def detect(cls, path) -> bool:
        raise NotImplementedError(f"{cls.__name__}.detect must be implemented")

    @classmethod
    def open_reader(cls, path, **kwargs):
        raise NotImplementedError(f"format {cls.name or cls.__name__!r} does not support reading")

    @classmethod
    def open_writer(cls, path, **kwargs) -> Writer:
        "A streaming :class:`Writer`; built-in writers take a ``mode`` from :data:`WRITE_MODES`."
        raise NotImplementedError(f"format {cls.name or cls.__name__!r} does not support writing")


@runtime_checkable
class Writer(Protocol):
    "Streaming writer: append episodes inside a ``with`` block."
    def __enter__(self) -> Writer: ...
    def __exit__(self, *exc) -> None: ...
    def write_episode(self, ep_data: dict) -> None: ...
    def write_episodes(self, episodes: Iterable[dict]) -> None: ...
