"""Load datasets by path, cache name or Hugging Face repo; convert, merge and normalize them (stable-worldmodel API)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/data/04_utils.ipynb.

# %% ../../nbs/data/04_utils.ipynb #94939658
# Adapted from stable-worldmodel's data package (https://github.com/galilai-group/stable-worldmodel):
#
# MIT License
#
# Copyright (c) 2026 GalilAI-group
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from __future__ import annotations

import json
import logging
import urllib.request
from pathlib import Path
from typing import Any

import numpy as np

from .dataset import Dataset, get_cache_dir
from .format import EPISODE_DATA_KEY, FORMATS, detect_format, get_format
from .normalization import (IdentityScaler, PercentileScaler, ZScoreScaler, ColumnTransform,
                                            get_scaler)

logger = logging.getLogger(__name__)
HF_BASE_URL = 'https://huggingface.co'

# %% auto #0
__all__ = ['logger', 'HF_BASE_URL', 'ensure_dir_exists', 'load_dataset', 'convert', 'merge', 'column_normalizer']

# %% ../../nbs/data/04_utils.ipynb #b05f1181
def ensure_dir_exists(path: Path):
    Path(path).mkdir(parents=True, exist_ok=True)


def load_dataset(name: str | Path, cache_dir: str | None = None, format: str | None = None, **kwargs: Any) -> Dataset:
    "Resolve `name` to a dataset and open it with its (detected, or given) format's reader, passing `kwargs`."
    name = str(name)
    if '://' in name:
        if format is not None:
            return get_format(format).open_reader(name, **kwargs)
        for fmt in FORMATS.values():
            if fmt.detect(name):
                return fmt.open_reader(name, **kwargs)
        raise ValueError(f"No format detected for {name!r}")
    path = _resolve_dataset(name, get_cache_dir(cache_dir, sub_folder='datasets'))
    if format is not None:
        return get_format(format).open_reader(path, **kwargs)
    fmt = detect_format(path)
    if fmt is None:
        raise ValueError(f"No format detected for {path!r}; pass format= explicitly.")
    return fmt.open_reader(path, **kwargs)


def _resolve_dataset(name: str, datasets_dir: Path) -> Path:
    "A local path for `name` (a path, a name in `datasets_dir`, or a Hugging Face repo id, downloaded)."
    local = Path(name).expanduser()
    if not local.is_absolute():
        local = datasets_dir / local
    for candidate in (local, local.with_name(local.name + '.h5')):
        if candidate.exists():
            return candidate
    if '/' in name and not name.startswith(('.', '/', '~')):
        return _resolve_dataset_hf(name, datasets_dir)
    raise FileNotFoundError(f"Cannot resolve {name!r}: not a local path or HF repo id.")


_HF_FILE_SUFFIXES = ('.h5', '.hdf5')
_HF_DIR_SUFFIXES = ('.lance',)


def _hf_list_tree(repo_id: str, sub_path: str = '') -> list[dict]:
    "The entries at ``<repo>/tree/main/<sub_path>`` (one Hugging Face API call)."
    url = f"{HF_BASE_URL}/api/datasets/{repo_id}/tree/main{'/' + sub_path if sub_path else ''}"
    with urllib.request.urlopen(url) as resp:
        return json.loads(resp.read())


def _hf_find_dataset_entry(repo_id: str) -> dict:
    "The first top-level dataset entry: a ``*.lance`` folder, else a ``*.h5`` / ``*.hdf5`` file."
    entries = _hf_list_tree(repo_id)
    for kind, suffixes in (('directory', _HF_DIR_SUFFIXES), ('file', _HF_FILE_SUFFIXES)):
        for entry in entries:
            if entry.get('type') == kind and entry.get('path', '').endswith(suffixes):
                return entry
    raise FileNotFoundError(f"No dataset found in HF repo {repo_id}: expected a top-level `*.lance` "
                            "directory or `*.h5` / `*.hdf5` file.")


def _hf_walk_files(repo_id: str, sub_path: str) -> list[str]:
    "Every file under `sub_path`."
    out, stack = [], [sub_path]
    while stack:
        for entry in _hf_list_tree(repo_id, stack.pop()):
            (stack if entry.get('type') == 'directory' else out).append(entry.get('path', ''))
    return out


def _resolve_dataset_hf(repo_id: str, datasets_dir: Path) -> Path:
    "The local copy of a Hugging Face dataset repo, downloaded on first use."
    local_dir = datasets_dir / repo_id.replace('/', '--')
    if local_dir.is_dir() and any(local_dir.iterdir()):
        logger.info(f"Using cached dataset for {repo_id} at {local_dir}")
        return local_dir
    logger.info(f"Downloading dataset {repo_id} from Hugging Face...")
    local_dir.mkdir(parents=True, exist_ok=True)
    entry = _hf_find_dataset_entry(repo_id)
    remotes = _hf_walk_files(repo_id, entry['path']) if entry.get('type') == 'directory' else [entry['path']]
    if not remotes:
        raise FileNotFoundError(f"HF repo {repo_id}: directory '{entry['path']}' is empty.")
    for remote in remotes:
        dest = local_dir / remote
        dest.parent.mkdir(parents=True, exist_ok=True)
        _download(f"{HF_BASE_URL}/datasets/{repo_id}/resolve/main/{remote}", dest)
    return local_dir


def _download(url: str, dest: Path) -> None:
    "Download `url` to `dest` (with a progress bar if tqdm is installed)."
    response = urllib.request.urlopen(url)
    total = int(response.headers.get('Content-Length', 0)) or None
    try:
        from tqdm import tqdm
        bar = tqdm(total=total, unit='B', unit_scale=True, desc=Path(dest).name)
    except ImportError:
        bar = None
    with open(dest, 'wb') as f:
        while chunk := response.read(1 << 16):
            f.write(chunk)
            if bar is not None: bar.update(len(chunk))
    if bar is not None: bar.close()

# %% ../../nbs/data/04_utils.ipynb #cfb424df
def _episode_steps(src, ep_idx: int) -> dict[str, list]:
    "Episode `ep_idx` of `src` as the ``{column: [row, ...]}`` writers take."
    length = int(src.lengths[ep_idx])
    if hasattr(src, 'offsets') and type(src).get_row_data is not Dataset.get_row_data:
        start = int(src.offsets[ep_idx])
        rows = src.get_row_data(list(range(start, start + length)))
        return {col: list(np.asarray(rows[col])) for col in src.column_names}
    return _episode_to_step_lists(src.load_episode(ep_idx), length)


def _episode_to_step_lists(ep: dict, ep_len: int) -> dict[str, list]:
    """
    A reader's episode (tensors) as ``{column: [row, ...]}``: channel-first images
    ``(T, C, H, W)`` back to ``(T, H, W, C)``, float images (``(T, H, W, C)`` or per agent
    ``(T, num_agents, H, W, C)``, values in ``[0, 1]``) to ``uint8``, scalars repeated.
    """
    out = {}
    for col, val in ep.items():
        if type(val).__module__.startswith('torch'):
            arr = val.detach().cpu().numpy()
        elif isinstance(val, np.ndarray):
            arr = val
        else:
            out[col] = [val] * ep_len
            continue
        if arr.ndim == 4 and arr.shape[1] in (1, 3):
            arr = arr.transpose(0, 2, 3, 1)
        if arr.dtype.kind == 'f' and arr.ndim in (4, 5) and arr.shape[-1] in (1, 3):
            arr = (np.clip(arr, 0.0, 1.0) * 255.0).astype(np.uint8)
        out[col] = list(arr)
    return out


def _with_episode_data(src, ep_idx: int, steps: dict, carry: bool) -> dict:
    if carry:
        steps[EPISODE_DATA_KEY] = {k: v[0] for k, v in src.get_episode_data([ep_idx]).items()}
    return steps


def _progress(it, desc: str, progress: bool):
    if not progress:
        return it
    try:
        from tqdm import tqdm
        return tqdm(it, desc=desc)
    except ImportError:
        return it


def convert(
    source: str | Path,
    dest: str | Path,
    *,
    source_format: str | None = None,
    dest_format: str = 'hdf5',
    cache_dir: str | None = None,
    progress: bool = True,
    **dest_kwargs: Any) -> None:
    """
    Rewrite the dataset `source` (anything :func:`load_dataset` takes) at `dest` in `dest_format`,
    episode by episode; `dest_kwargs` go to the writer (e.g. ``mode``, ``compression``).
    Episode-scoped data is kept if the destination format supports it.
    """
    src = load_dataset(source, cache_dir=cache_dir, format=source_format)
    writer_cls = get_format(dest_format)
    ep_cols = list(getattr(src, 'episode_column_names', None) or [])
    carry = bool(ep_cols) and getattr(writer_cls, 'supports_episode_data', False)
    if ep_cols and not carry:
        logger.warning(f"convert: '{dest_format}' does not support episode data; dropping {ep_cols}.")
    episodes = (_with_episode_data(src, i, _episode_steps(src, i), carry)
                for i in _progress(range(len(src.lengths)), f'Converting -> {dest_format}', progress))
    with writer_cls.open_writer(dest, **dest_kwargs) as writer:
        writer.write_episodes(episodes)


def merge(
    sources,
    dest: str | Path,
    *,
    dest_format: str = 'hdf5',
    source_formats: list[str | None] | None = None,
    mode: str = 'error',
    cache_dir: str | None = None,
    progress: bool = True,
    **dest_kwargs) -> None:
    """
    Write the episodes of every source, in order, into one dataset at `dest` (episodes renumbered
    ``0 .. N-1``). The sources must have the same columns (checked before anything is written).
    `mode`: ``'error'`` if `dest` exists (default), ``'overwrite'`` or ``'append'``.
    """
    sources = list(sources)
    if len(sources) < 2:
        raise ValueError("merge needs at least two source datasets")
    if source_formats is not None and len(source_formats) != len(sources):
        raise ValueError("source_formats must align with sources")
    fmt = lambda i: source_formats[i] if source_formats else None
    writer_cls = get_format(dest_format)

    reference = ep_reference = ref_source = None
    for i, source in enumerate(sources):
        ds = load_dataset(source, cache_dir=cache_dir, format=fmt(i))
        cols, ep_cols = set(ds.column_names), set(getattr(ds, 'episode_column_names', None) or [])
        if reference is None:
            reference, ep_reference, ref_source = cols, ep_cols, source
            continue
        if cols != reference:
            raise ValueError(f"merge: column mismatch between {ref_source!r} and {source!r}: missing "
                             f"{sorted(reference - cols)}; unexpected {sorted(cols - reference)}. "
                             "All sources must share the same columns.")
        if ep_cols != ep_reference:
            raise ValueError(f"merge: episode-data column mismatch between {ref_source!r} and {source!r}: missing "
                             f"{sorted(ep_reference - ep_cols)}; unexpected {sorted(ep_cols - ep_reference)}.")
    carry = bool(ep_reference) and getattr(writer_cls, 'supports_episode_data', False)
    if ep_reference and not carry:
        logger.warning(f"merge: '{dest_format}' does not support episode data; dropping {sorted(ep_reference)}.")

    def episodes():
        for i, source in enumerate(sources):
            src = load_dataset(source, cache_dir=cache_dir, format=fmt(i))
            for ep_idx in _progress(range(len(src.lengths)), f'Merging {source}', progress):
                yield _with_episode_data(src, ep_idx, _episode_steps(src, ep_idx), carry)
            if hasattr(src, 'close'):
                src.close()

    with writer_cls.open_writer(dest, mode=mode, **dest_kwargs) as writer:
        writer.write_episodes(episodes())

# %% ../../nbs/data/04_utils.ipynb #b21b89d7
def column_normalizer(dataset: Dataset, source: str, target: str, method: str = 'zscore') -> ColumnTransform:
    """
    A dataset ``transform`` normalizing column `source` into `target`, with a scaler
    (``'zscore'``, ``'percentile'`` or ``'none'``) fitted on the whole column.
    """
    scaler = get_scaler(method)
    if method != 'none':
        scaler.fit(np.array(dataset.get_col_data(source)))
    return ColumnTransform(scaler, source=source, target=target)
