"""Probes attached to world models, to read quantities out of their latent space (stable-worldmodel API)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/wm/07_probes.ipynb.

# %% ../../nbs/wm/07_probes.ipynb #2434cd22
# Adapted from stable-worldmodel's world models package (https://github.com/galilai-group/stable-worldmodel):
#
# MIT License
#
# Copyright (c) 2026 GalilAI-group
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from __future__ import annotations

from pathlib import Path

import torch
from torch import nn

# %% auto #0
__all__ = ['attach_probe', 'get_probe', 'load_probe']

# %% ../../nbs/wm/07_probes.ipynb #9fca7a2f
def attach_probe(model: nn.Module, key: str, probe: nn.Module):
    "Attach `probe` (e.g. a linear readout of the latent) to `model` under `key` (saved with the model)."
    assert isinstance(probe, nn.Module), 'Probe must be a nn.Module'
    if not hasattr(model, '_probes'):
        model._probes = nn.ModuleDict()
    model._probes[key] = probe


def get_probe(model: nn.Module, key: str) -> nn.Module | None:
    "The probe attached to `model` under `key`, or None."
    if hasattr(model, '_probes'):
        return model._probes[key] if key in model._probes else None
    return None


def load_probe(model: nn.Module, key: str, path: str | Path):
    "Load a probe saved at `path`: a whole module (attached under `key`) or the state dict of the probe under `key`."
    payload = torch.load(path, map_location='cpu', weights_only=False)
    if isinstance(payload, nn.Module):
        attach_probe(model, key, payload)
    elif isinstance(payload, dict):
        probe = get_probe(model, key)
        if probe is None:
            raise ValueError(f'No probe found for key {key} in model')
        probe.load_state_dict(payload)
