"""VMAS scenarios (vectorized multi-robot simulator) as stable-marl environments, with vector observations."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/envs/vmas/00_env.ipynb.

# %% ../../../nbs/envs/vmas/00_env.ipynb #0760304b
from __future__ import annotations

from typing import Any

import numpy as np
from gymnasium import spaces

from ..base import MultiAgentEnv
from ...types import AgentID

# %% auto #0
__all__ = ['VmasEnv']

# %% ../../../nbs/envs/vmas/00_env.ipynb #b66591fc
def _gymnasium_space(space) -> spaces.Space:
    "A gymnasium copy of one of VMAS's gym spaces."
    kind = type(space).__name__
    if kind == 'Box':
        return spaces.Box(np.asarray(space.low, np.float32), np.asarray(space.high, np.float32), dtype=np.float32)
    if kind == 'Discrete':
        return spaces.Discrete(int(space.n))
    if kind == 'MultiDiscrete':
        return spaces.MultiDiscrete(np.asarray(space.nvec))
    raise TypeError(f"unsupported VMAS space {space}")


def _numpy(value):
    value = value.detach().cpu().numpy()[0] if hasattr(value, 'detach') else np.asarray(value)[0]
    return value.item() if np.ndim(value) == 0 else value


class VmasEnv(MultiAgentEnv):
    """
    The VMAS `scenario` (one of ``vmas.scenarios`` / ``vmas.mpe_scenarios``) as a stable-marl env.

    Parameters
    ----------
    scenario : str
        VMAS scenario, e.g. 'navigation', 'transport', 'simple_spread'
    continuous_actions : bool
        Continuous (VMAS's default) or discrete actions
    max_steps : int
        Step limit (truncation); VMAS's default is none
    device : str
        Torch device of the simulation
    **scenario_kwargs
        The scenario's arguments, e.g. ``n_agents=4``
    """
    def __init__(self, scenario: str, continuous_actions: bool = True, max_steps: int = 100, device: str = 'cpu',
                 **scenario_kwargs):
        import vmas
        self.scenario = scenario
        self._env = vmas.make_env(scenario, num_envs=1, device=device, continuous_actions=continuous_actions,
                                  dict_spaces=True, terminated_truncated=True, max_steps=max_steps, **scenario_kwargs)
        self.agent_names = [agent.name for agent in self._env.agents]
        self.num_agents = len(self.agent_names)
        self.continuous_actions = continuous_actions
        obs = [_gymnasium_space(self._env.observation_space[n]) for n in self.agent_names]
        acts = [_gymnasium_space(self._env.action_space[n]) for n in self.agent_names]
        self.obs_dims = [int(np.prod(s.shape)) for s in obs]                # each agent's true sizes
        self.action_dims = [int(np.prod(s.shape)) for s in acts]
        D = max(self.obs_dims)
        self.observation_space = spaces.Dict({a: spaces.Dict({'vector': spaces.Box(-np.inf, np.inf, (D,), np.float32)})
                                              for a in range(self.num_agents)})
        if continuous_actions:
            K = max(self.action_dims)
            pad = lambda x, d: np.concatenate([x.reshape(-1), np.zeros(K - d, np.float32)])
            self.action_space = spaces.Dict({a: spaces.Box(pad(s.low, d), pad(s.high, d), dtype=np.float32)
                                             for a, (s, d) in enumerate(zip(acts, self.action_dims))})
        else:
            if len({str(s) for s in acts}) > 1:
                raise ValueError(f"{scenario}: the agents' discrete action spaces differ ({acts}); use continuous actions")
            self.action_space = spaces.Dict({a: s for a, s in enumerate(acts)})

    @property
    def noop_action(self):
        "Zero force (continuous), or VMAS's action 0 (no movement)."
        return np.zeros(self.action_space[0].shape, np.float32) if self.continuous_actions else 0

    @property
    def state_space(self) -> spaces.Space:
        "Position and velocity of every entity: (num_entities, 2 * dim)."
        n, d = len(self._env.world.entities), self._env.world.dim_p
        return spaces.Box(-np.inf, np.inf, (n, 2 * d), np.float32)

    def state(self) -> np.ndarray:
        return np.stack([np.concatenate([_numpy(e.state.pos), _numpy(e.state.vel)])
                         for e in self._env.world.entities]).astype(np.float32)

    def _observations(self, obs) -> dict[AgentID, dict]:
        D = max(self.obs_dims)
        out = {}
        for a, name in enumerate(self.agent_names):
            v = np.asarray(_numpy(obs[name]), np.float32).reshape(-1)
            out[a] = {'vector': np.concatenate([v, np.zeros(D - len(v), np.float32)])}
        return out

    def _infos(self, info) -> dict[AgentID, dict]:
        return {a: {k: _numpy(v) for k, v in info[name].items()} for a, name in enumerate(self.agent_names)}

    def reset(self, seed: int | None = None, options: dict | None = None):
        super().reset(seed=seed)
        obs, info = self._env.reset(seed=seed, return_info=True)
        return self._observations(obs), self._infos(info)

    def step(self, actions: dict[AgentID, Any]):
        import torch
        act = {}
        for a, name in enumerate(self.agent_names):
            x = np.asarray(actions[a])
            if self.continuous_actions:
                act[name] = torch.as_tensor(x.reshape(-1)[:self.action_dims[a]], dtype=torch.float32)[None]
            else:
                act[name] = torch.as_tensor(x.astype(np.int64)).reshape(1, *self.action_space[a].shape)
        obs, rewards, terminated, truncated, info = self._env.step(act)
        term, trunc = bool(terminated[0]), bool(truncated[0])
        agents = range(self.num_agents)
        reward = lambda r: float(np.asarray(_numpy(r)).reshape(-1)[0])   # (1,) or (1, 1) depending on the scenario
        return (self._observations(obs), {a: reward(rewards[n]) for a, n in enumerate(self.agent_names)},
                {a: term for a in agents}, {a: trunc for a in agents}, self._infos(info))
