"""`stable_marl.wrapper`: the wrappers under stable-worldmodel's package name."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/wrapper/02_init.ipynb.

# %% auto #0
__all__ = ['AddPixelsWrapper', 'EnsureGoalInfoWrapper', 'EnsureImageShape', 'EnsureInfoKeysWrapper', 'EverythingToInfoWrapper',
           'MapKeysWrapper', 'MegaWrapper', 'ResizeGoalWrapper', 'TransformInfoWrapper']

# %% ../../nbs/wrapper/02_init.ipynb #4a70e5e5
import importlib

from ..wrappers.default import (AddPixelsWrapper, EnsureGoalInfoWrapper, EnsureImageShape,
                                          EnsureInfoKeysWrapper, EverythingToInfoWrapper, MapKeysWrapper, MegaWrapper,
                                          ResizeGoalWrapper, TransformInfoWrapper)


def __getattr__(name: str):
    "Everything else (the visual wrappers, loaded lazily) from `stable_marl.wrappers`."
    if name.startswith('__'):
        raise AttributeError(name)
    return getattr(importlib.import_module('stable_marl.wrappers'), name)

_all_ = ['AddPixelsWrapper', 'EnsureGoalInfoWrapper', 'EnsureImageShape', 'EnsureInfoKeysWrapper',
         'EverythingToInfoWrapper', 'MapKeysWrapper', 'MegaWrapper', 'ResizeGoalWrapper', 'TransformInfoWrapper']
