"""`stable_marl.wrapper.default`: `stable_marl.wrappers.default` under stable-worldmodel's module name."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/wrapper/00_default.ipynb.

# %% auto #0
__all__ = []

# %% ../../nbs/wrapper/00_default.ipynb #690ff56a
from ..wrappers.default import *   # noqa: F401,F403
from ..wrappers.default import __all__
