"""`stable_marl.wrapper.visual`: `stable_marl.wrappers.visual` under stable-worldmodel's module name (imports OpenCV)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/wrapper/01_visual.ipynb.

# %% auto #0
__all__ = []

# %% ../../nbs/wrapper/01_visual.ipynb #52b776c8
from ..wrappers.visual import *   # noqa: F401,F403
from ..wrappers.visual import __all__
