"""Policies a `World` can run."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/policy/02_init.ipynb.

# %% auto #0
__all__ = ['Policy', 'ExpertPolicy', 'RandomPolicy']

# %% ../../nbs/policy/02_init.ipynb #765db806
from .base import Policy, ExpertPolicy
from .random import RandomPolicy

_all_ = ['Policy', 'ExpertPolicy', 'RandomPolicy']
