"""What a `World` runs: one action per env and agent from the stacked observations."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/policy/00_base.ipynb.

# %% ../../nbs/policy/00_base.ipynb #d1161b33
from __future__ import annotations

from typing import TYPE_CHECKING, Any

import numpy as np

from ..envs.base import MultiAgentEnv

if TYPE_CHECKING:
    from stable_marl.world.env_pool import EnvPool

# %% auto #0
__all__ = ['Policy', 'ExpertPolicy']

# %% ../../nbs/policy/00_base.ipynb #d9229fcb
class Policy:
    """
    Base class of the policies a :class:`World` runs.

    A policy sees the stacked observations of an :class:`EnvPool` (a dict of arrays of shape
    ``(num_envs, num_agents, ...)``) and returns one action per env and agent, as an array of
    shape ``(num_envs, num_agents)``.
    """
    def __init__(self):
        self.env: EnvPool | None = None

    def set_env(self, env: EnvPool):
        "Attach the pool of envs this policy acts in."
        self.env = env

    def reset(self, mask: np.ndarray):
        "Called when the envs where `mask` is True start a new episode (for stateful policies)."

    def get_action(self, obs: dict[str, Any]) -> np.ndarray:
        "Actions of shape (num_envs, num_agents) for the stacked observations `obs`."
        raise NotImplementedError

# %% ../../nbs/policy/00_base.ipynb #7f75f939
class ExpertPolicy(Policy):
    """
    Base class of privileged (scripted) policies, which read each env's true state instead of
    the observations, e.g. a shortest-path planner used to collect expert datasets.

    Subclasses implement :meth:`act`, the actions of all agents of one env.
    """
    def get_action(self, obs: dict[str, Any]) -> np.ndarray:
        return np.array([self.act(env) for env in self.env.envs])

    def act(self, env: MultiAgentEnv) -> np.ndarray:
        "Actions of the agents of `env`, of shape (num_agents,)."
        raise NotImplementedError
