"""Uniformly random actions, seeded for reproducibility."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/policy/01_random.ipynb.

# %% ../../nbs/policy/01_random.ipynb #8f1a9a61
from __future__ import annotations

from typing import Any

import numpy as np
from gymnasium import spaces

from .base import Policy

# %% auto #0
__all__ = ['RandomPolicy']

# %% ../../nbs/policy/01_random.ipynb #e17bdb97
class RandomPolicy(Policy):
    "Samples every agent's action uniformly from its (discrete) action space."
    def __init__(self, seed: int | None = None):
        super().__init__()
        self.seed = seed
        self.rng = np.random.default_rng(seed)

    def get_action(self, obs: dict[str, Any]) -> np.ndarray:
        action_space = self.env.action_space
        actions = np.empty((self.env.num_envs, self.env.num_agents), dtype=np.int64)
        for a in range(self.env.num_agents):
            space = action_space[a]
            if not isinstance(space, spaces.Discrete):
                raise TypeError(f"RandomPolicy only supports Discrete action spaces, got {space}")
            actions[:, a] = space.start + self.rng.integers(space.n, size=self.env.num_envs)
        return actions
