"""Planning costs of rolled-out trajectories, joint `(B, S)` or per agent `(B, S, num_agents)`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/planning/01_objective.ipynb.

# %% ../../nbs/planning/01_objective.ipynb #7875e048
# Adapted from stable-worldmodel's planning package (https://github.com/galilai-group/stable-worldmodel):
#
# MIT License
#
# Copyright (c) 2026 GalilAI-group
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F

from ..protocols import Objective

# %% auto #0
__all__ = ['GoalMSE', 'ControlPenalty', 'WeightedSum']

# %% ../../nbs/planning/01_objective.ipynb #b0225e44
def _reduce(err: torch.Tensor, reduction: str, per_agent: bool, agent_dim: int) -> torch.Tensor:
    "Collapse every axis after the candidate one (keeping `agent_dim` if `per_agent`)."
    dims = tuple(d for d in range(2, err.ndim) if not (per_agent and d == agent_dim))
    return err.sum(dim=dims) if reduction == 'sum' else err.mean(dim=dims)


class GoalMSE(nn.Module):
    """
    Squared error between the last predicted embedding ``predicted_emb`` ``(B, S, T, ...)``
    and the last goal embedding ``goal_emb`` ``(B, T_goal, ...)``.

    Returns ``(B, S)``, or ``(B, S, num_agents)`` with ``per_agent=True``, where the agent axis
    of the embeddings is `agent_dim` (3: ``(B, S, T, num_agents, ...)``).
    """
    def __init__(self, pred_key: str = 'predicted_emb', goal_key: str = 'goal_emb', reduction: str = 'sum',
                 per_agent: bool = False, agent_dim: int = 3):
        super().__init__()
        if reduction not in ('sum', 'mean'):
            raise ValueError(f"reduction must be 'sum' or 'mean', got {reduction!r}")
        self.pred_key, self.goal_key, self.reduction = pred_key, goal_key, reduction
        self.per_agent, self.agent_dim = per_agent, agent_dim

    def forward(self, info_dict: dict) -> torch.Tensor:
        pred = info_dict[self.pred_key]
        goal = info_dict[self.goal_key][:, None, -1:].expand_as(pred)
        err = F.mse_loss(pred[:, :, -1:], goal[:, :, -1:].detach(), reduction='none')
        return _reduce(err, self.reduction, self.per_agent, self.agent_dim)


class ControlPenalty(nn.Module):
    """
    Squared norm of the action candidates ``(B, S, horizon, num_agents, ...)``: ``(B, S)``, or
    ``(B, S, num_agents)`` with ``per_agent=True``.
    """
    def __init__(self, action_key: str = 'action_candidates', per_agent: bool = False, agent_dim: int = 3):
        super().__init__()
        self.action_key, self.per_agent, self.agent_dim = action_key, per_agent, agent_dim

    def forward(self, info_dict: dict) -> torch.Tensor:
        return _reduce(info_dict[self.action_key].pow(2), 'sum', self.per_agent, self.agent_dim)


class WeightedSum(nn.Module):
    "Linear combination ``sum(w * term(info_dict))`` of objectives (all joint or all per agent)."
    def __init__(self, terms: list[tuple[float, Objective]]):
        super().__init__()
        if not terms:
            raise ValueError("WeightedSum requires at least one term")
        self.weights = [weight for weight, _ in terms]
        self.objectives = nn.ModuleList(term for _, term in terms)

    def forward(self, info_dict: dict) -> torch.Tensor:
        return sum(weight * term(info_dict) for weight, term in zip(self.weights, self.objectives))
