"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../../nbs/envs/multigrid/core/01_actions.ipynb.

# %% auto #0
__all__ = ['Action', 'NavigationAction']

# %% ../../../../nbs/envs/multigrid/core/01_actions.ipynb #1a0ed7b6
import enum

# %% ../../../../nbs/envs/multigrid/core/01_actions.ipynb #acee5d39
class Action(enum.IntEnum):
    """
    Enumeration of possible actions.
    """
    left = 0 #: Turn left
    right = enum.auto() #: Turn right
    forward = enum.auto() #: Move forward
    pickup = enum.auto() #: Pick up an object
    drop = enum.auto() #: Drop an object
    toggle = enum.auto() #: Toggle / activate an object
    done = enum.auto() #: Done completing task


# %% ../../../../nbs/envs/multigrid/core/01_actions.ipynb #d4cf5410
class NavigationAction(enum.IntEnum):
    """
    Enumeration of possible navigation actions.
    """
    left = 0 #: Turn left
    right = enum.auto() #: Turn right
    forward = enum.auto() #: Move forward
    done = enum.auto() #: Done completing task
